overlay/frameworks/base/core/res/res/values/config.xml

due to only shinano and kitakami have it enabled on powerHAL and Kernel
we do not want see it on unsupported targets

sony-common: remove TapToWake overlay

---

sepolicy/init.te

Avoid
03-01 18:50:37.286 W/init    (1): type=1400 audit(0.0:4): avc: denied { write } for name=wcnss_wlan dev=tmpfs ino=11360 scontext=u:r:init:s0 tcontext=u:object_r:wcnss_device:s0 tclass=chr_file permissive=0

rhine: Fix wifi with Enforcing SELinux

---

sepolicy/touchfusion.te

This fixes those denied:
[   17.038652] touch_fusion: start [/system/vendor/bin/touch_fusion] 4
[   17.038783] type=1400 audit(198323.169:3): avc:  denied  { net_admin } for  pid=478 comm="touch_fusion" capability=12  scontext=u:r:touchfusion:s0 tcontext=u:r:touchfusion:s0 tclass=capability permissive=1
[   17.042344] type=1400 audit(198323.169:4): avc:  denied  { sys_nice } for  pid=478 comm="touch_fusion" capability=23  scontext=u:r:touchfusion:s0 tcontext=u:r:touchfusion:s0 tclass=capability permissive=1
Signed-off-by: Julien Bolard <jbolard@genymobile.com>

Fix touchscreen on Z4 when SELinux is enforced in 'user' build

---

sepolicy/file_contexts

this is needed for SELinux in bcmdhd devices

sony-common: update file_contexts

---

rootdir/init.common.rc
sepolicy/addrsetup.te
sepolicy/init.te
sepolicy/tad.te
sepolicy/tad_static.te

This patch removes duplicate tad_static domain and
uses tad domain instead of it.
Also, it makes tad as a permissive domain since it requires
specific block_device permissions that are labeled as
neverallow android rule.
Change-Id: If88fde7ac13736fcd714891fe61eda4757b77116

common: Fix tad_static denials

---

sepolicy/kernel.te

It is required for touch_fusion
<5>[   11.389866] type=1400 audit(14553972.959:5): avc:  denied  { net_admin } for  pid=375 comm="touch_fusion" capability=12  scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=0
<5>[   11.406476] type=1400 audit(14553972.969:6): avc:  denied  { write } for  pid=375 comm="touch_fusion" path="/dev/kmsg" dev="tmpfs" ino=11268 scontext=u:r:kernel:s0 tcontext=u:object_r:tmpfs:s0 tclass=file permissive=0
<5>[   11.425711] type=1400 audit(14553972.999:7): avc:  denied  { write } for  pid=375 comm="touch_fusion" path="/dev/kmsg" dev="tmpfs" ino=11268 scontext=u:r:kernel:s0 tcontext=u:object_r:tmpfs:s0 tclass=file permissive=0
<5>[   11.456219] type=1400 audit(14553973.029:8): avc:  denied  { write } for  pid=375 comm="touch_fusion" …

common: sepolicy: Fix kernel denials

---

sepolicy/init.te

<5>[   11.241711] type=1400 audit(14553972.809:4): avc:  denied  { write } for  pid=374 comm="init" name="kmsg" dev="tmpfs" ino=11268 scontext=u:r:init:s0 tcontext=u:object_r:tmpfs:s0 tclass=file permissive=0
Change-Id: I364bed09218789e191ffbe14b3fcbd88b088d690

common: sepolicy: Fix init denied

---

rootdir/init.common.usb.rc

pick from satsuki 6.0 release 32.1.A.1.163

sony-common: Add MIDI comp for USB state

---

overlay/frameworks/base/core/res/res/values/config.xml

families like yukon rhine and kanuti have not the support for it right now .... also it is defined on targets

sony-common: prevent Double TaptoWake be enabled on all

---

common.mk

david@david-desktop:~$ adb devices
List of devices attached
192.168.1.3:5555         device
HOW TO USE
adb connect target_ip:5555

sony-common: add ADBoverWIFI prop

---

liblights/lights.c

This lights HAL was originally written for Sony's own LED driver, and later we hacked in the blink functionality, but this still wasn't great.
Because we're simply using the QCOM LED driver, we can switch to the AOSP/CAF lights HAL, and modify for the extra Sony functionality (mostly thermanager scaling).
This is now working well, with clean on/off blinking.

Improve liblights

---

sepolicy/file_contexts
sepolicy/tad.te

Add TA block device labelled then fix tad denials for generic block_device.
According to Google the better solution here is to just add a specific
label to the block device. Allowing access to the generically
labeled "block_device" (in external/sepolicy) is dangerous.
Change-Id: I4e2f66e9b31c82ee4433f8531529570dd1433667

sony: common: sepolicy: Fix tad denials

---

sepolicy/system_app.te

In accordance with AOSP's new system/sepolicy repo

remove system_data_file due to new neverallow rule

---

common.mk

needed by https://github.com/sonyxperiadev/device-sony-common/blob/master/rootdir/system/vendor/etc/audio_effects.conf#L211

sony-common: Set property for dualmic fluence for voice communication

---

common.mk

https://android.googlesource.com/platform/frameworks/av/+/439e4ed408c21bd65711d279bd5251cef7e83440
DEEP_BUFFER uses very low latency and as compress_offload (which is better) it can let's help in battery life while using music streams services

sony-common: use deep buffer for music stream

---

common.mk

This is a package for telephony targets ... not needed to be included in windy devices

sony-common: move out InCallUI

---

sepolicy/gatekeeperd.te
sepolicy/keystore.te

Fixes the following on kitakami devices
```
type=1400 audit(220125.139:3): avc: denied { read } for pid=454 comm="gatekeeperd" name="kmota.mdt" dev="mmcblk0p3" ino=28 scontext=u:r:gatekeeperd:s0 tcontext=u:object_r:firmware_file:s0 tclass=file permissive=1
type=1400 audit(220125.149:4): avc: denied { open } for pid=454 comm="gatekeeperd" path="/firmware/image/kmota.mdt" dev="mmcblk0p3" ino=28 scontext=u:r:gatekeeperd:s0 tcontext=u:object_r:firmware_file:s0 tclass=file permissive=1
type=1400 audit(220125.149:5): avc: denied { getattr } for pid=454 comm="gatekeeperd" path="/firmware/image/kmota.mdt" dev="mmcblk0p3" ino=28 scontext=u:r:gatekeeperd:s0 tcontext=u:object_r:firmware_file:s0 tclass=file permissive=1
type=1400 audit(220125.199:6): avc: denied { read } for pid=448 comm="keystore" …
```

Allow gatekeeperd and keystore access to /firmware files

---

sepolicy/file.te
sepolicy/file_contexts
sepolicy/fingerprintd.te

/sys/bus/spi/devices/spi0.1/spi_prepare still has some issues - it gets swooped up by the generic sysfs rules and denied - ideas appreciated?

Allow fingerprintd access to devices/sysfs required for kitakami fingerprint

---

fingerprint/Android.mk
fingerprint/QSEEComAPI.h
fingerprint/QSEEComFunc.c
fingerprint/QSEEComFunc.h
fingerprint/README.md
fingerprint/fingerprint.c
fingerprint/fpc_imp.c
fingerprint/fpc_imp.h
fingerprint/tz_api.h

* This was based around the OnePlus Two TrustZone fingerprint HAL (found here
https://github.com/CyanogenMod/android_device_oneplus_oneplus2/blob/cm-13.0/fingerprint)
* Extra information was obtained from the Nexus 6P (angler kernel driver) (found here
https://android.googlesource.com/kernel/msm/+/3d0a564505ab8452e7e6f52b972db386cc2f5f69)
* Protocol informations was verified as it passed through the QSEECOM API to linux kerne
Authors Jens Andersen & Shane Francis

Add Kitakami fingerprint HAL

---

common.mk

Reverts sonyxperiadev/device-sony-common#45
If its enabled video playback on chrome is broken on html5 videos 
It stutters all the time here 
It happens on all shinano devices

Revert "sony-common: enable video offload"

---

common.mk

android.hardware.telephony.gsm.xml is not needed by windy targets
android.hardware.sensor.gyroscope.xml is not needed by eagle

Sony-common: remove permissions

---

rootdir/init.common.rc

Enable qmuxd service on wifi-only devices
Modem files from Stock are needed on windy too !!

Fix GPS on windy-devices

---

CommonConfig.mk
power/power.c
system.prop

Core limiting via msm_performance works well, but cpuquiet absolutely
hates it. rqbalance is not aware of msm_performance so it spams dmesg
because it cannot online a core for 'unknown' reasons.
We can achieve the same result using cpuquiet which rqbalance is
aware of. We can also have two sources of core limiting, power
profile and thermal.
We also need to tune rqbalance and cpuquiet per platform so also
move their system props.

Move sysfs and props for cpuquiet hotplugging

---

power/power.c

nr_max_cpus is always the lower of nr_power_max_cpus and
nr_thermal_max_cpus but their default values are 0. Currently only
thermanager sets the nr_thermal_max_cpus and only when it needs
thermal mitigation. If we set only one then the other will always
be 0 causing problems.

power: init thermal maximum before setting normal profile

---

common.mk

actual kernel is using 0x8010 which is black see:
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.BF64.1.1_rb1.27/drivers/media/platform/msm/vidc/msm_vdec.c#L26
actual media hal 5.1.1_r37 is using 0x8080 see:
https://android.googlesource.com/platform/hardware/qcom/media/+/android-5.1.1_r37/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp#129
aligned this from userspace using:
https://android.googlesource.com/platform/hardware/qcom/media/+/android-5.1.1_r37/mm-video-v4l2/vidc/vdec/src/omx_vdec_msm8974.cpp#1754

sony-common: use proper black conceal color

---

rootdir/init.common.rc

It is required for timekeep.
sonyxperiadev/timekeep#8

sony: common: init: Add timekeep dependencies

---

rootdir/init.common.rc

01-01 23:46:04.353   325   325 E qdutils : setIdleTimeout:Unable to open /sys/devices/virtual/graphics/fb0/idle_time node Permission denied

sony-common: Update Graphics Permissions

---

CommonConfig.mk

Controls whether or not per-CPU power values are used in determining
task placement. If this is disabled, tasks are simply placed on the
smallest capacity CPU that will adequately meet the task's needs as
determined by the task load tracking mechanism. If this is enabled,
after a set of CPUs are determined which will meet the task's
performance needs, a CPU is selected which is reported to have the
lowest power consumption at that time.
Change-Id: Ia3f53b8c712f872a1029a9a401020a2e8263eac0

sony: common: Enable sched_enable_power_aware at boot stage

---

fingerprint/Android.mk

This help us to keep inline with some external projects like CAF
this is needed for people building with kernel-headers isntad of common-kernel-headers repo

sony-common: add kernel-headers for inline kernel build system

---

CommonConfig.mk

this makes more easy the build for CAF and AOSP building with inline kernel-headers build system

sony-common: make common-headers repo not mandatory for build

---

rootdir/init.common.rc

this is needed for fm downloaderPatch in CAF or AOSP

sony-common: creates fm directory

---

brcm_fmradio/Android.mk
brcm_fmradio/brcm-uim-sysfs/Android.mk
brcm_fmradio/brcm-uim-sysfs/brcm_hci_dump.c
brcm_fmradio/brcm-uim-sysfs/btsnoop.c
brcm_fmradio/brcm-uim-sysfs/include/brcm_hci_dump.h
brcm_fmradio/brcm-uim-sysfs/include/btsnoop.h
brcm_fmradio/brcm-uim-sysfs/include/uim.h
brcm_fmradio/brcm-uim-sysfs/include/utils.h
brcm_fmradio/brcm-uim-sysfs/include/v4l2_cfg.h
brcm_fmradio/brcm-uim-sysfs/uim.c
brcm_fmradio/brcm-uim-sysfs/upio.c
brcm_fmradio/brcm-uim-sysfs/utils.c
brcm_fmradio/fmradio.v4l2-fm/Android.mk
brcm_fmradio/fmradio.v4l2-fm/v4l2_fm.c
brcm_fmradio/fmradio.v4l2-fm/v4l2_ioctl.c
brcm_fmradio/fmradio.v4l2-fm/v4l2_ioctl.h
brcm_fmradio/libfmjni/Android.mk
brcm_fmradio/libfmjni/android_fm.cpp
brcm_fmradio/libfmjni/android_fm.h
brcm_fmradio/libfmjni/android_fmradio_Receiver.cpp
brcm_fmradio/libfmjni/android_fmradio_Receiver.h

Needed for Broadcom BT/FM combo chip kernel driver.
Allow use FMRadio on devices with broadcom stack.
brcm-uim-sysfs from sony opensource package.
FMRadio-jni from https://android-review.googlesource.com/#/c/46100/
libfmradio.v4l2-fm, Author: marco.sinigaglia@csr.com

Add broadcom fm radio stuff

---

brcm_fmradio/Android.mk

this avoid errors with QCOM-FM lib

sony-common: BCM-FM: allow only BCM devices

---

rootdir/init.common.rc

this allows using ES alongside with the custom implementation some
custom roms use.

common: Rename adb over network com property

---

fingerprint/fpc_imp_kitakami.c

Just fix code style which was missed during the m-mr1 branch copying process.

[master] sony: common: fpc: Fix code style

---

rootdir/init.common.rc

https://android.googlesource.com/platform/system/core/+/android-6.0.1_r68/rootdir/init.rc#21
why this .... Debugfs exists as a simple way for kernel developers to make information
available to user space also it is not enabled in android-6.0.1_r66 tag and not more in N but for
development purposes it is needed here .....

sony-common: update debugfs mount as AOSP

---

fingerprint/fpc_imp_loire.c

1. Disable device after init and capture
2. Fix "wait for finger lost"

Fix bugs on loire fpc

---

CommonConfig.mk

Controls whether or not per-CPU power values are used in determining
task placement. If this is disabled, tasks are simply placed on the
smallest capacity CPU that will adequately meet the task's needs as
determined by the task load tracking mechanism. If this is enabled,
after a set of CPUs are determined which will meet the task's
performance needs, a CPU is selected which is reported to have the
lowest power consumption at that time.
Change-Id: Ia3f53b8c712f872a1029a9a401020a2e8263eac0

[m-mr1] sony: common: Enable sched_enable_power_aware at boot stage

---

fingerprint/fingerprint.c
fingerprint/fpc_imp_kitakami.c

This fixes the system freezing when an error occurs..
HOWEVER:
This does NOT fix the TZ crash we are occasionally seeing

Fingerprint: Improve error checking to avoid freezing system

---

common.mk

Write the bluetooth macaddr to a place that is natively readable
by bluetooth services, instead of creating new locations which
requires excessive permissions.

macaddr: remove dangerous sepolicy permissions

---

Android.mk

DisplayHAL and MediaHAL need this
needed by commits: 44ecd1d - 0e5dbd2
needed by: hardware/qcom/media/msm8996/mm-video-v4l2/vidc/vdec/Android.mk:ifeq ($(call is-platform-sdk-version-at-least, 22),true)
picked needed part from: https://source.codeaurora.org/quic/la/device/qcom/common/tree/utils.mk?h=LA.UM.5.5.c1-00600-8x96.0

sony-common: add build utils for HALs

---

CommonConfig.mk
seccomp/mediacodec-seccomp.policy

7.1 now makes use of minijail on kernel versions newer than 3.8, this seccomp policy allows mediaserver / meidacodecs access to the needed syscalls

Setup seccomp policy

---

brcm_fmradio/libfmjni/Android.mk

it is required for shinano devices.

sony: common: brcm fm: Fix library path for non 64 bits targets

---

brcm_fmradio/brcm-uim-sysfs/include/uim.h

Use the same AOSP value for UART ioctl line discipline (N_BRCM_HCI).
Change-Id: I0f9fbeb9d406ffa9e28fef82aad81758650fd419

sony: common: brcm bt fm: Set 25 for N_BRCM_HCI

---

overlay/packages/apps/Bluetooth/res/values/config.xml

read more about:
http://www.android-rsap.com/bluetooth-sim-access-profile.html
http://www.android-rsap.com/compatibility.html
http://www.android-rsap.com/41-support/139-compatibility-sony.html

[NEED TEST]sony-common: bluetooth: enable Sim Access Profile (SAP)

---

rootdir/init.common.rc

To allow netmgrd to acquire wakelocks correctly
we need to ensure that it belongs to system group
Bug: 24546055
Change-Id: I00b9effa7351f1cd8ef9fc062de12b5276254801

sony-common: add system group to netmgrd process

---

overlay/frameworks/base/core/res/res/values/config.xml

sony-common: use rounded icons when available

---

android_filesystem_config.h

mm-qcamera-daemon needs to set a sensor thread to SCHED_FIFO in order to
guarantee sensor event delivery uniformity.
Bug: 26255266
Change-Id: Iab0a148bbc24e4fc30d93363380fe6548529dee3

sony-common: Grant mm-qcamera-daemon CAP_SYS_NICE.

---

common.mk

on android 7 we have to use HAL3 as default
Signed-off-by: Alin Jerpelea <alin.jerpelea@sonymobile.com>

switch to camera HAL3

---

brcm_fmradio/brcm-uim-sysfs/include/uim.h

it is a 3.18 kernel requirement.
Change-Id: I958a6b3ecb01b6d8f3c2ee629bba23c273d9dcdf

[master] sony: common: Update BT FM sysfs path

---

common.mk

https://android.googlesource.com/platform/system/core/+/android-7.0.0_r24/sdcard/sdcard.c#96

sony-common: enable sdcardFS support

---

rootdir/init.common.rc

Bug: 25864142
Change-Id: Ief59e26ce63b341115d42d0145a43a845b1645da

sony-common: Use GID "wakelock" to control access to kernel wakelock

---

overlay/frameworks/base/core/res/res/values/config.xml

https://android.googlesource.com/platform/frameworks/base/+/android-6.0.1_r77/core/res/res/values/config.xml#661
This allows flip covers such as the Sony Smart Style Cover
to suspend or wake the device.

sony-common: Allow lid to control sleep/wake behaviour

---

init/Android.mk
init/config.mk

* Avoid showing the 'info device-sony-common-init:' on lunch config
* Handle the missing DEV_BLOCK_FOTA_NUM in init/Android.mk
* Fix an error appearing on 6.0 build/ involving TARGET_ARCH detection
Change-Id: Ic11d39b81013413c84aefef255a7e802ceb17a73
Signed-off-by: Adrian DC <radian.dc@gmail.com>

common: init: Rewrite and fix the init_sony configuration safeties

---

common.mk

from kernel ISP uses boot time https://github.com/sonyxperiadev/kernel/commit/80c65b30f9e9e3b01ac9c39b30d813248f4b0d05
set boot time as default
HAL1 8974
12-27 10:27:51.063  5594  5630 D CAM_MemoryQuery: timestamp=159955, availMem=866, totalMem=1687, totalPSS=15, lastTrimLevel=0, largeMemoryClass=512, nativePSS=2, dalvikPSS=6, otherPSS=7,threshold=144, lowMemory=false
12-27 10:27:51.493   396  5677 D mm-camera: mct: start_sof_check_thread: Starting SOF timeout thread
12-27 10:27:55.883   396  5677 D mm-camera: mct: stop_sof_check_thread: Stopping SOF timeout thread
HAL3 8994
12-27 10:34:11.786  5206  5341 D CAM_MemoryQuery: timestamp=278646, availMem=1729, totalMem=2696, totalPSS=31, lastTrimLevel=0, largeMemoryClass=512, nativePSS=8, dalvikPSS=12, otherPSS=11,threshold=216, …

sony-common: cameraHAL: Advertize correct timestamp source

---

Android.mk

* The HAL in hardware/qcom/wlan/qcwcn is blocked
under TARGET_BOARD_AUTO, therefore it needs
to be explicitely called for devices needing it
Change-Id: Ia97b656d4ee01507c79f5ed267f045265d7ec8f0
Signed-off-by: Adrian DC <radian.dc@gmail.com>

common: hals: Add WLAN qcwcn HAL inclusion

---

common.mk

Do not use prebuilt libs anymore

Sony-common: build gps location from repo

---

CommonConfig.mk

when you connect AC charger (when device is off) the display show battery charge image (AOSP) and then it rest on
this help us to fix it ... unfortunatelly when you hold power button to see charge image again the display rest on again

sony-common: disable CHARGER_INIT_BLANK

---

fingerprint/fpc_imp_loire.c

evice/sony/common/fingerprint/fpc_imp_loire.c:44:33: warning: unused parameter 'sb_size' [-Wunused-parameter]
uint32_t sb_size)

sony-common: fpc: loire: fix warning in build

---

common.mk

This reverts commit 255373136ae19af395eeff0d996f2787ba974643.
sometimes after record 1080p videos and playback the display rest freeze at first frame

Revert "sony-common: cameraHAL: Advertize correct timestamp source"

---

Android.mk

rhine uses 8960
kanuti uses 8992

sony-common: build: configure BT for 8916

---

Android.mk

with this you are saying GOOD BYE QCOM encoders/decoders
FIX IT

sony-common: fix mediaHAL path

---

brcm_fmradio/brcm-uim-sysfs/uim.c

Please see https://github.com/sonyxperiadev/kernel/pull/1162
This is the required user space modification (1/2) for combined BT/FMRadio support via the broadcom ldisc driver.

[WIP] BT/FMRadio using the broadcom ldisc driver

---

brcm_fmradio/brcm-uim-sysfs/uim.c

This allows to pass the brcm device node to libbt (uses UartPort) such
that the BT data flow is routed through the kernel ldisc driver. As a
consequence parallel use of BT & FMRadio is possible. The Uim service
needs to be aware of the "real" Uart device node instead.
Use the same naming as in I2c0c8f3016415fac5f2c68b9a33a75b2687d8a87
Change-Id: I08a1c72f3955429fa7c8d93e57f219782b1db467
Signed-off-by: Alexander Diewald <Diewi@diewald-net.com>

Rename brcm_fmradio parameter UartPort to UimUartPort.

---

overlay/frameworks/base/core/res/res/values/config.xml

RadioAccessFamily only selects RAF_GSM, not the grouped GSM.
See https://github.com/android/platform_frameworks_base/blob/master/telephony/java/android/telephony/RadioAccessFamily.java#L363

overlay: Enable GPRS and EDGE

---

brcm_fmradio/brcm-uim-sysfs/upio.c
common.mk

Rename rfkilldisabled to rfkilldisableduim in the parsing code
of UIM such that we can set rfkilldisabled in the build.prop to
stop android's bt implementation to mess around with the chip's
power states.
This allows to enable BT while the FMRadio is on.
Change-Id: I6639e21ee4c1ca592ed70f417c825ed2a987be71
Signed-off-by: Alexander Diewald <Diewi@diewald-net.com>

common: Rename & set rfkilldisabled property for brcm_fmradio.

---

CommonConfig.mk

if BOARD_USE_ENFORCING_SELINUX := true is defined then you will use Enforcing SELinux

sony-common: add guard to selinux

---

common.mk

Tone does not have BCM BT/FM at all.
Change-Id: Id6d72d6ec484c1ef05cd94880f86a425a0332faa

sony: common: tone: Remove BCM BT/FM requirement

---

healthd/healthd_board_sony.cpp

Taken from: 
- https://android.googlesource.com/platform/system/core/+/android-7.1.2_r5/healthd/healthd_mode_charger.cpp#476
- https://android.googlesource.com/platform/system/core/+/android-7.1.2_r5/healthd/healthd_mode_charger.cpp#274
- https://android.googlesource.com/platform/system/core/+/android-7.1.2_r5/healthd/healthd_mode_charger.cpp#280
The following functions were updated to include pointer:
```
void gr_font_size(const GRFont* font, int *x, int *y);
int gr_measure(const GRFont* font, const char *s);
void gr_text(const GRFont* font, int x, int y, const char *s, bool bold);
```
System/core/healthd/healthd_mode_charger.cpp uses `gr_sys_font()` representing `const GRFont* font`

Fix Healthd build error due to missing pointer [7.1.2]

---

common.mk

This should be set per platform and not common
This reverts commit afbffe4a17dbbe95dbb0e278a38b9d0fbf068db1.

Revert "enable fluence"

---

common.mk

this libs is a dependency for the new libril used by the new libs for android 7.0
Change-Id: Ic4e7ab93d521673de874abd8ac7310829d674d65

common: RIL: build libprotobuf-cpp-full

---

rootdir/init.common.usb.rc

Kernel 4.4 supports ONLY ConfigFS (so no FunctionFS) and it is
enabled by default, hence we need to configure it accordingly.
Please note that this change can be valid also on kernel 3.18,
where ConfigFS USB gadget can be activated, but FunctionFS is
enabled by default.

[k4.4 - READ COMMENT] init.common.usb.rc: Complete rewrite for USB ConfigFS gadget

---

CommonConfig.mk

This cmdline option is now platform-specific: on kernel 4.4
Tone needs it disabled.
This option is moved to platform configuration.

[COMMON] Remove the platform-specific lpm_levels cmdline

---

rootdir/init.common.rc

RQBalance-PowerHAL PowerServer will create it automatically
but, for some reason, on some Android versions the directory
will be created with wrong permissions.
Fix this by paranoidly ensuring directory creation and by doing
permission changes at init time.
IMPORTANT NOTE:
Do NOT use "mkdir powerhal 0773 system system": as I wrote,
the directory may be already there at that time!!

[URGENT] [COMMON] Ensure directory creation and correct perms for PowerServer

---

rootdir/init.common.rc

This daemon is responsible for FastRPC offloading from CPU to
Hexagon DSP. This is actually a strict requirement for ACDB
calibrations to work for phone calls (otherwise ADSP fails).

[COMMON] Add the QC FastRPC adsprpc daemon

---

power/rqbalance_halext.c

During some commit porting for final release, a logic inversion happened in the search functions, but that change was not reflected in the usage of one of those functions in new_lock_init, producing a complete breakage of the RQBalance-PowerHAL locking logic and Advanced Power Hints.
This fix has been tested on SoMC Maple and has to be merged ASAP for decreasing heat and power consumption in the handled cases.

[URGENT] RQBalance-PowerHAL locking logic fix

---

rootdir/init.common.usb.rc

The folder /config is already created at this point in the boot process, so no need to do that again.
Not only that, but the permissions declared in the mkdir call are wrong for Android.
Android can then not write to /config, and as a result cannot configure /config/sdcardfs.
Change-Id: I001f73adcebb550748ce18fc40b69033ba1e5aa4

rootdir: init.common.usb.rc: remove unneeded mkdir call

---

rootdir/init.common.rc

It should be added per platform.
Change-Id: Id6eead02b09ef902e1c5678ca66584e2c68f35f8

sony: common: init: Remove max_comp_streams

---

init/Android.mk

* Introduced in AOSP master in platform/external/toybox,
commit I589c4a248e135c6c0e25aadd063717c87369ef40,
toybox_static is now part of the AOSP original packages,
therefore adapt the binary's location and use it
Change-Id: I0b861de24c24efe47bbff1d8ae80c7c818d77b9c

init: Adapt toybox_static location for AOSP O

---

healthd/Android.mk
power/Android.mk

Now we need to include system/core/include as well because of
nested header inclusion changes, at least in frameworks/native and
also, some headers were moved to proper locations (minui etc).

[COMMON] healthd: Fix includes for Android 8.0

---

healthd/healthd_board_sony.cpp

charger mode use reboot(), not android_reboot()

sony: healthd: fix build

---

rootdir/init.common.rc

Makes this consistent with other targets and maken sure
any changes in healthd will be transparent to targets as long
as the symlink is maintained.
Update the seclabel accordingly too.
Test: Tested charge-only mode on angler
Change-Id: Ic71e32f52c39bc45eae8d2552259695934592fc7
Signed-off-by: Sandeep Patil <sspatil@google.com>

use /charger symlink to launch healthd

---

rootdir/init.common.rc

kugo:/vendor/bin/hw # ls
android.hardware.configstore@1.0-service  android.hardware.media.omx@1.0-service  rild  wpa_supplicant

sony-common: fix rild-daemon2

---

seccomp_policy/mediacodec.policy

04-19 12:43:38.399   587   587 W /system/bin/mediaextractor: libminijail[587]: compile_file: nonexistent syscall '_llseek'

sony-common: seccomp: remove unneeded llssek syscall

---

rootdir/system/vendor/etc/audio_effects.conf

sony-common: libeffects: move all libraries to vendor

---

rootdir/init.common.rc

following commit https://android.googlesource.com/platform/system/nfc/+/d482d7c489603ecbbb8eb5bb4d69e2024eb46217%5E%21/#F0

sony-common: Restrict HAL implementation access to only /data/vendor/nfc

---

overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml

in case of build gapped rom on bcm devices having bt enabled cause reboots
disable BT by default ... it can be enabled by user after pass Initial configuration
refer: https://android.googlesource.com/platform/frameworks/base/+/8c18431be868e0960e80638c1a974d71a0df05b4%5E%21/#F0

sony-common: disable BT by default

---

rootdir/system/vendor/etc/audio_effects.conf

09-07 22:46:33.131   533   533 W EffectsFactory: checkLibraryPath() corrected library path /system/vendor/lib/soundfx/libbundlewrapper.so to /vendor/lib/soundfx/libbundlewrapper.so
09-07 22:46:33.137   533   533 W EffectsFactory: checkLibraryPath() corrected library path /system/vendor/lib/soundfx/libreverbwrapper.so to /vendor/lib/soundfx/libreverbwrapper.so
09-07 22:46:33.143   533   533 W EffectsFactory: checkLibraryPath() corrected library path /system/vendor/lib/soundfx/libvisualizer.so to /vendor/lib/soundfx/libvisualizer.so
09-07 22:46:33.151   533   533 W EffectsFactory: checkLibraryPath() corrected library path /system/vendor/lib/soundfx/libqcomvisualizer.so to /vendor/lib/soundfx/libqcomvisualizer.so
09-07 22:46:33.152   533   533 W EffectsFactory: checkLibraryPath() corrected …

sony-common: fix audio effects warnings in logs

---

common.mk

needed by some apps due to renderscript

sony-common: make sure include librsjni.so

---

treble.mk

include impl and service to binderize them in future via manifest.xml
this is needed by GPS HAL

sony-common: add GNSS HAL

---

librqbalance/rqbalance_ctl.c
power/power.h
rootdir/init.common.rc

Having the socket for PowerServer under /data caused issues with
encryption where cryptfs would try to unmount /data, but would fail
because the power hal would still hold its socket open.
Move the socket over to /dev/socket/rqbalance/ to avoid such issues, and
to also keep it together with other sockets.

rqbalance: move socket path out of /data

---

rootdir/init.common.rc

Use CAP_NET_BIND_SERVICE instead
following marlin

sony-common: drop net_raw group

---

rootdir/init.common.rc

on aosp we are not using HDMI also on legacy platforms it was symlinked to FB1 if you see at
msm8956-mdss.dtsi
msm8996-mdss.dtsi
msm8998-mdss.dtsi
the new platforms are using hdmi under FB2 not FB1

sony-common: remove unneeded HDMI symlink

---

healthd/Android.mk
rootdir/init.common.rc

also remove LOCAL_PROPRIETARY_MODULE from healthd since it is root file and not system one

sony-common: move services to vendor

---

overlay/frameworks/base/core/res/res/values/config.xml

on android oreo the launcher can set adaptive icons per app .... this flag is not needed anymore

sony-common: remove round icons overlay flag

---

common.mk

sony-common: enable libmmlib2d_interface

---

rootdir/init.common.rc

ExtendedSettings now implements the new DispCal functionality
and it requires to access the required kernel sysfs to work.
Assign correct permissions.

[COMMON] init.common.rc: Add permissions for DispCal

---

rootdir/init.common.rc

sony-common: add graphics perms for bootanimation

---

init/Android.mk

init_sony is a workaround for Sony devices that are not able
to reboot to FOTAKernel by "reboot recovery" command or such.
Since we have already "fixed" such behaviour on loire and tone,
this helper becomes redundant for those platforms and should
not be built by default

init: Add init_sony build barrier

---

treble.mk

simple ... mapper has not init service
check
https://android.googlesource.com/platform/hardware/interfaces/+/android-8.0.0_r15/graphics/mapper/2.0/default/

common: remove not needed mapper service

---

healthd/healthd_board_sony.cpp

The battery capacity reporting from battery power_supply could be a
default value before BMS initialization done. This causes an incorrect
battery capacity being showed up at the beginning frames of off-mode
charging. Check whether the soc reporting is ready before entering into
off-mode charging.
CRs-Fixed: 1042133
Change-Id: I35d9308dc56d7d4acfbad74ddccd53a64afb53ce

healthd: Check SoC status before entering off-mode charging

---

CommonConfig.mk
android_filesystem_config.h

This is needed to rebuild odm partition with correct file access rights

[MASTER] Override filesystem config

---

CommonConfig.mk
android_filesystem_config.h

This is needed to rebuild odm partition with correct file access rights

[N-MR1] Override filesystem config

---

treble.mk

Test: Manual use of Camera, Movies, Photos and YouTube apps.
Test: With CtsMediaTestCases.apk installed,
adb shell am instrument -e size small -w
'android.media.cts/android.support.test.runner.AndroidJUnitRunner'
Bug: 31399200
Change-Id: I6c027a29e5336d1834f6f5ee9f555e5c39834c3c

Disable Treble OMX by default.

---

android_filesystem_config.h

Bluetooth driver needs to hold a wakelock while receiving
packets from the UART to make sure that no bytes are lost.
Test: Bluetooth on/off
Bug: 63628397
Change-Id: I8cd6a13921cdc2777c64b0624f544a9548292522
(cherry picked from commit 0c2b5e803d9655007d664937b179e36c37178956)

Bluetooth: Allow wakelock access to wcnss_filter

---

common.mk
rootdir/Android.mk
rootdir/vendor/bin/rdclean.sh
rootdir/vendor/etc/init/rdclean.rc

This adds ramdump cleaner for loire & tone & yoshino platforms. Please note that it depends on selinux change specific for the each platform, uploaded separately.

ramdump cleaner - common part

---

rootdir/init.common.usb.rc

remove not exist instances (needs more clean) also fix rndis sys needed for usb tethering
poplar:/config/usb_gadget/g1/functions # ls
accessory.gs2  audio_source.gs2  cser.dun.0  cser.nmea.1  ffs.adb  gsi.dpl  gsi.rmnet  gsi.rndis  midi.gs5  mtp.gs0  ncm.0  ptp.gs1
poplar:/config/usb_gadget/g1/configs/b.1 # ls
MaxPower  bmAttributes  f2  strings

sony-common: usb.rc: cleanup

---

rootdir/init.common.rc

The macaddrsetup service creates a file in this directory containing the bluetooth MAC address that needs to be readable by the bluetooth service. Ensure files created here are in the bluetooth group.

Fixes for creating MAC address files on Oreo

---

manifest.xml
treble.mk

The service is causing random issues upon boot, these include:
1. compass not working at all
2. compass returning errant values, even after calibration
3. all sensors not working
Remove the service for now, until the proprietary sensors frameworks is
updated to be compatible.
Change-Id: If6452423a5ae14a70005830a23500553075f697c

treble: remove sensors service

---

CommonConfig.mk

This causes issues with custom ROMs that explicitly enforce
position independent code, so that dalvik execution from /data
for /system APKs can be disabled.
Since they may also provide prebuilt APKs (F-Droid, Silence
etc.) that live on the /system partition, we should not force
this build time preference onto users.
Furthermore we have a huge amount of space on /system, and first
boot is significantly faster when all APKs are processed at build.
Effectively, The only thing this flag does is slow down developers
when they want to test a clean boot.
This reverts commit 3d3e040342e906d260c943bd55be4e2f137132df.

Revert "do not dexpreopt prebuilts"

---

rootdir/init.common.srv.rc

* Do not grant thermanager dac_override capability
* Add thermanager to 'system' group
Change-Id: I4cff1444715427f33ebe2d8185f4ec6fd5a95b52

sony: common: sepolicy: Resolve thermanager dac_override

---

common.mk
rootdir/init.common.rc

Odmcheck will block init until exited. If a mismatch between odm partition and the build props is detected a warning screen will be shown. Currently this warning screen just has a simple placeholder UI with the version information shown on a blue background. The warning screen will be shown for 10 seconds, then the boot will resume regardless. Once everything is in place and works fine, after changing a build flag, odmcheck will instead shutdown the device after the 10 seconds.

Initial odmcheck (1/4)

---

rootdir/init.common.rc
rootdir/init.common.srv.rc

Do not grant timekeep dac_override capability by adding the service
to the system group and also set /data/time permission.
Change-Id: Ife6e672352f8ab4b8e12bfe893463b4984bd3448

[master] sony: common: sepolicy: Resolve timekeep dac_override denial

---

rootdir/init.common.srv.rc

Access /data/misc/sensors/debug and /data/system/sensors/settings
This requires system when selinux security is enforced
at least on tone platform.
Change-Id: I10685a43bf92e403210c904117edfabbb990a006

[master] sony: common: Add system group|user to sensors service

---

rootdir/init.common.rc

fix debugfs mount statement as per the following two upstream commits:
```
remote: https://source.codeaurora.org/quic/la/device/qcom/common
branch: qcom-devices.lnx.1.0.r15-rel
4d5f58b init: Mount debugfs by default
ed099c1 init.qcom.rc: Mount debugfs with correct permissions
```

Fix debugfs mount statement

---

rootdir/init.common.srv.rc

Setting ioprio to realtime within rmt_stroage requires unnecessarily
granting CAP_SYS_ADMIN, which is a highly privileged superuser
capability.
Having init set ioprio at service launch removes the need for
granting this capability and keeps rmt_storage unprivileged.
Addresses the following errors:
07-20dd 14:21:03.867   824   824 W rmt_storage: type=1400 audit(0.0:4):
avc: denied { sys_admin } for capability=21 scontext=u:r:rmt_storage:s0
tcontext=u:r:rmt_storage:s0 tclass=capability permissive=0
07-20 14:21:03.874   824   824 E rmt_storage: Error setting io priority
to CLASS_RT (1)
Test 1 and 2 below verify that my change results in the intended
behavior. Test 3 is a sanity check to show the state without
granting CAP_SYS_ADMIN and to demonstrate that my change results
in the intended …

[master] sony: common: init: set ioprio to realtime for rmt_storage

---

rootdir/init.common.rc
rootdir/init.common.srv.rc

This issue is still present on tone platform.
So set ats_2 file permission and avoid the requirement
to add dac_override entry in selinux rules.
Change-Id: I3906789bdfed0bc0fa549046d50b5605282baa88

[master] sony: common: init: Fix dac_override for timekeep definitely

---

rootdir/init.common.rc

Also, do not call swap mount until completed boot process
This help to save ~50ms in boot time and bootanim shown time
Reference:
https://android.googlesource.com/device/google/wahoo/+/06b4b0ce139eea0e015184297cedbbbc9cf2d8d3
Change-Id: Ic63fb53689d7da8ca948cedfd4f41d9869f64033

[master] sony: common: Move fstab mount process to common

---

rootdir/init.common.rc

1 .Fix tone boot process by removing bootanimation service call
2. Remove duplicate stage.
Change-Id: If249d460ee945cc5a856567cb8005bc5fb519563

[master] sony: common: Do not start bootanimation early

---

rootdir/init.common.rc

Already set in 'on early-boot' block.

Remove duplicate RLIMIT_MEMLOCK

---

rootdir/init.common.rc

Already set in 'on early-boot' block.

[o-mr0] Remove duplicate RLIMIT_MEMLOCK

---

CommonConfig.mk

These flags are common for all of our current platforms, and when we migrating to the Image.lz4-dtb in the future we will not need to update each platform repository separately. If it's will be merged these flags can be and will be removed from PlatformConfig.mk on each platform.

[o-mr0] Add common flags for all current platforms

---

CommonConfig.mk

These flags are common for all of our current platforms, and when we migrating to the Image.lz4-dtb in the future we will not need to update each platform repository separately. If it's will be merged these flags can be and will be removed from PlatformConfig.mk on each platform.

[master] Add common flags for all current platforms

---

rootdir/init.common.rc

this command prevents the encryption policy from being set correctly
on the directory `/data/data` when a device first boots in FBE mode.

Drop "mkdir /data/data/media"

---

common.mk
rootdir/Android.mk

Ramdump partition is available on all modern qcom SoC's,
even on a msm8939. So clean ramdump partition can be used
on all devices and there is no sense in using this barrier.

[o-mr0] Remove build barrier for clean ramdump partition

---

common.mk
rootdir/Android.mk

Ramdump partition is available on all modern qcom SoC's,
even on a msm8939. So clean ramdump partition can be used
on all devices and there is no sense in using this barrier.

[master] Remove build barrier for clean ramdump partition

---

Android.mk
common.mk
treble.mk

The msm8994 gps hal we are using is obsolete. Switch to using a more up-to-date hal.
Change-Id: I4449e66f772c298a040d71cf8d3aca14b290aa07

[DONOTMERGE] gps: switch to an updated hal

---

rootdir/init.common.rc

It is still breaking boot process for tone platform.
Change-Id: Iad230f13a9f14d4d03472f06af670cf5dfc507c7

[master] sony: common: init: Do not call bootanim services early

---

rootdir/init.common.rc

It is still breaking boot process for tone platform.
Change-Id: Iad230f13a9f14d4d03472f06af670cf5dfc507c7

[o-mr0] sony: common: init: Do not call bootanim services early

---

overlay/frameworks/base/core/res/res/values/config.xml

Android now reads gps config from resources, and the default values do not work for sony devices.
Override the defaults with values that work on sony devices.
Change-Id: Ic1f1f7427d5747205e1a9cd2566473fba0f88d32

overlay: config: add gps config overlay

---

rootdir/vendor/etc/init/sensors.rc

Adding NET_BIND_SERVICE capability to sensors service causes it to crash with a sigtrap.
Removing it fixes that issue, and the service seems to run fine afterwards.
Change-Id: I60d5723ec07d4c8f06be8e164ddbacdb315bb437

rootdir: vendor: services: remove capablities from sensors service

---

android_filesystem_config.h

Camera daemon is no longer used and can be deprecated.

[master] Remove camera daemon rule from android_filesystem_config

---

android_filesystem_config.h

Camera daemon is no longer used and can be deprecated.

[o-mr0] Remove camera daemon rule from android_filesystem_config

---

CommonConfig.mk

The new WITH_DEXPREOPT_BOOT_IMG_AND_SYSTEM_SERVER_ONLY flag introduced in o-mr1 makes it possible to only pre-optimize boot and system_server related dex code.
Use the flag to avoid SELinux denials related to system_server trying to access dalvik/art cache from /data, while having other system dex code optimized at runtime.
This should also help save some space on /system.
Thanks to LuK1337@github for the hint!
Change-Id: I026b7fa8b2a4b270ff44cab71bd1e6d304ef3c6b

CommonConfig: only pre-optimize boot classpath and system_server jars

---

rootdir/init.common.rc

Add system group to the charger service and avoid
selinux denials.
avc:  denied  { dac_override } for  pid=465 comm="charger" capability=1
scontext=u:r:charger:s0 tcontext=u:r:charger:s0
tclass=capability permissive=0
Also, set service as critical.
If the charger service doesn't work properly
then we'll be able to check what's wrong with it
by reading pstore if it is a critical service.
If the service is not critical then we'll get a freezing boot splash
which will not help in nothing for users and developers.

[master] sony: common: init: Fix dac override for charger

---

rootdir/init.common.rc

The macaddrsetup service creates a file in this directory containing
the wifi MAC address that needs to be readable by the wireless
service. Ensure files created here are in the wifi group.

[n-mr1] common.rc: Use setgid on /data/misc/wifi

---

common.mk
rootdir/vendor/etc/public.libraries.txt

Android needs this text file to know what libraries are allowed to be loaded by apps directly.
For now, add:
libOpenCL.so to the list, in order to get OpenCL to function properly.
adsprpc related libraries, since they were also declared public in stock.
Change-Id: I15ef7a7ab7d1f1a0cc6b484cd2ca9993f40de23b

rootdir: vendor: add public.libraries.txt

---

rootdir/vendor/etc/init/netmgrd.rc

The boot trigger gets executed before the filesystems are ready. If an
encrypted filesystem is used, it is not yet mounted at the time of execution of
the boot trigger. This causes problems with "forceencrypt" settings in the
fstab, as the partition is also encrypted on the first boot and directories
can never be created at all.
sonyxperiadev/bug_tracker#78

common.rc: Create netmgrd dirs on /data in post-fs-data not of boot trigger

---

rootdir/init.common.rc

This path allows system and odm to be mounted early which
have .rc files and critical services that are called/required
from boot process.
There is a race condition during offline charger service call as following:
When its dependencies are declared in vendor then we have the service loading error:
[    2.189134] charger: android charging is enabled
[    2.202449] EXT4-fs (mmcblk0p52): mounted filesystem with ordered data mode. Opts: barrier=1
[    2.207436] EXT4-fs (mmcblk0p28): mounted filesystem with ordered data mode. Opts: barrier=1
[    2.207589] init: do_start: Service rmt_storage not found
[    2.207648] init: do_start: Service mlog_qmi_service not found
[    2.207745] init: do_start: Service irsc_util not found
[    2.207809] init: processing action (charger) from …

[master] sony: common: init: Fix charger dependencies

---

rootdir/init.common.rc

This group is necessary for charger service which will fix selinux denials
as following:
avc:  denied  { dac_override } for  pid=475 comm="charger" capability=1
scontext=u:r:charger:s0 tcontext=u:r:charger:s0
tclass=capability permissive=0
avc:  denied  { dac_read_search } for  pid=475 comm="charger" capability=2
scontext=u:r:charger:s0 tcontext=u:r:charger:s0 tclass=capability permissive=0
Signed-off-by: Humberto Borba <humberos@omnirom.org>
Change-Id: I5b0354be45ee5ae036ca12f4a04765354fab21cc

[master] sony: common: init: Fix dac_override denial for charger

---

common-prop.mk

* It's enabled by default since 8.0.0

Remove ro.sys.sdcardfs property

---

CommonConfig.mk

this is not more common since nile (SDM660) has not cache partition
move this to platform

sony: common: remove cache build flag

---

manifest.xml

03-19 04:35:23.787   568   568 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.radio@1.0::IRadio/slot2 in either framework or device manifest.
03-19 04:35:23.804   568   568 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.radio.deprecated@1.0::IOemHook/slot2 in either framework or device manifest.

common: add slot2 for radio and radio.deprecated

---

common-packages.mk

* Vendor specific tinycompress is explicitly built in the audio HAL.
* See : https://android.googlesource.com/platform/hardware/qcom/audio/+/android-8.1.0_r15/hal/Android.mk#92
Change-Id: I8e25e4e5da141e9aad5646cb551fa85d772181f1

Drop redundant audio package

---

common.mk

Overlays only for framework-res will be converted into RROs.
Other overlays can't be converted due to some known issues on app RRO.
Bug: 36231603
Change-Id: Idca30fdbbcc990fd124de16a06a112a346612a61
(cherry picked from commit db1b6058200fc5255f519cf6609fca7619d6743e)

Enforce RRO on framework-res

---

hardware/qca_cld3/Android.mk

sdm660 has wlan_mac.bin placed on /persist partition and it should be linked to /data
this fixes the unknown IP address

wifi: fix wifi on nile

---

common-treble.mk

* android.hardware.camera.provider@2.4-impl depends on it
thus we don't need to add it to product packages manually.

Remove `camera.device@3.2-impl` from product packages

---

hardware/liblights/Android.mk

This is needed by inline kernel system 

lights: re-add kernel headers dependencies

---

CommonConfig.mk

Set TARGET_USES_MKE2FS := true to use new EXT4 tool chain
Bug: 62421233
Test: walleye boots with new parition
Change-Id: Id6e5c68b2d7854e5330ad87443b974361a4bff9d

vold: Use mke2fs to create ext4 images

---

rootdir/vendor/etc/init/hw/init.common.rc

newer devices use another video instance like video2

init: remove video symlinks

---

hardware/liblights/Android.mk
hardware/liblights/Light.cpp

Devices with projection unit require the new Micro Communicator
to manage the same.
Add support to send the backlight events to the MicroComm to
be able to manage the projection light on these devices.
This support gets enabled only when TARGET_USES_UCOMM_BACKLIGHT.

[COMMON] hardware: liblights: Add support for MicroCommunicator backlight

---

hardware/liblights/Light.cpp

* For some reason our driver doesn't really like
duty pcts that are like: "0,0,0,0,0,0,0,0" breaking
custom colors in RGB sync blink.
* Returning "0" instead fixes that issue.

Return "0" as duty pcts when brightness is equal 0

---

misc/version/Android.mk

If we use different definitions chances are that we run into missmatches even if we don't want to.
Also, SOMC_KERNEL_VERSION is undefined.

common: Unify ro.odm.* definition

---

rootdir/vendor/etc/init/xtra.rc

The service xtra-daemon service is not necessary for gps functionality.
Confirmed by clearing AGPS data, removing the service and then rebooting and trying to get a lock. The time to first fix (TTFF) wasn't drastically affected by the service removal.

rootdir: vendor: init: remove xtra.rc

---

rootdir/vendor/etc/init/netmgrd.rc

all the things were move to /data/vendor/netmgr and we should not add permissions
for the old location

netmgr: remove legacy /data/misc/netmgr folder

---

hardware/power/power.c

* Due to missing break we'd be returning "unknown"
instead of compat_string or type_string.

PowerHAL: Add missing break

---

hardware/power/expatparser.c
hardware/power/power.c
hardware/power/power.h
overlay/frameworks/base/core/res/res/values/config.xml

Since version 7.0, Android supports a sustained performance
power hint for long-running applications, like games,
camera (in our case, viewfinder, photos but video encoding
keeps its own hint), RenderScript and audio processing:
in these cases the device requires to keep an high performance
state which will produce a lot of heat and, after a while,
the performance will decrease due to thermal mitigations.
To address this issue, handle the sustained performance hint
to limit the performance of the device to an acceptable level
while avoiding overheat.
This patchset also implements userspace management for the new
RQBalance kerneldriver's Cluster Frequency Limits functionality.
Now we support setting limits on minimum and/or maximum frequency
for all clusters by specifying that on any …

[RQB-POWER] Sustained performance and Cluster Frequency Limits (rqb-cfl)

---

rootdir/vendor/etc/init/hw/init.common.rc

06-21 12:34:40.007   646   646 W SDM     : HWDevice::SysFsWrite: Open failed = /sys/devices/virtual/graphics/fb2/hpd

init: add missing FB2 perms

---

common-prop.mk

Since there's a lack of proprietary support for color transforms, allow client to handle it.

Disable persist.hwc2.skip_client_color_transform

---

rootdir/Android.mk

for TWRP we can use init.recovery.xxx.rc for usb and init

allow overriding init.recovery.common.rc

---

CommonConfig.mk
common.mk

for ex:
actually if anyone sets BOARD_USE_ENFORCING_SELINUX := true
in Customization.mk this is called after and has not effect

common: call cust makefiles early

---

common-packages.mk

The thermal management has moved to kernel from userspace.
Do not include thermanager in that case to avoid conflicts.
Change-Id: I2dc3eb387fab34b0fc155453f22a35f86c8ebfbd

packages: do not include thermanager for kernel version 4.9

---

hardware/qcom/Android.mk

Use the SOMC_KERNEL_VERSION flag to pick the appropriate BT HAL:
- msm8998 for k4.4
- sdm845    for k4.9

[master] hardware: qcom: Move BT HAL under SOMC_KERNEL_VERSION ifeq

---

CommonConfig.mk

It is created according to BOARD_ROOT_EXTRA_SYMLINKS in BoardConfig.mk and PlatformConfig.mk.
Creating both the /dsp directory and the /dsp symlink would cause the symlink to be /dsp/dsp.

Do not create the dsp directory since it is created by all platforms which need it, as a symlink.

---

common.mk

PRODUCT_DEFAULT_DEV_CERTIFICATE should be used to specify the new
location of testkey.  Prior to this change, some apks were still being
signed with keys from build/make/target/product/security.
Note that setting PRODUCT_DEFAULT_DEV_CERTIFICATE does not effect what
verity key is used (so the build is still using
build/make/target/product/security/verity).

Fix dev-keys configuration

---

common-treble.mk

This value is ignored and overwritten based on
`PRODUCT_FULL_TREBLE_OVERRIDE` or `PRODUCT_SHIPPING_API_LEVEL`, and thus has
no reason to be set in our makefile.
Relevant build section:
https://android.googlesource.com/platform/build/+/2b32469c47378c3e655e0ef4057ce15a824b184a/core/config.mk#693
In the future we may want to enable this again by setting `PRODUCT_SHIPPING_API_LEVEL`, as soon as it's fully compatible.

treble: Remove misleading PRODUCT_FULL_TREBLE := true

---

hardware/qcom/Android.mk

* We are no longer building libbt-vendor
therefore it's not necessary to set it.

Remove bt-hal from pathmap

---

common-packages.mk

* We are using QTI bluetooth HAL therefore
libbt-vendor isn't used for anything.

Drop libbt-vendor

---

overlay/frameworks/base/core/res/res/values/config.xml

include GoogleCamera
inlcude AOSPCamera see https://android.googlesource.com/platform/packages/apps/Camera2/+/35ad43aeb0d810f1ce104d17556f447743756673%5E%21/#F0

Add camera package to default dnd access list

---

rootdir/vendor/etc/init/hw/init.common.rc
rootdir/vendor/etc/init/sensors.rc

Sensor is intermittent on suzu@loire due to some
race condition at services initialization.
So this patch is moving sensor service from main class to late_start
and also adding a property condition for its initialization.
on property:sys.qcom.devup=1
Now service starts with no problem.
Change-Id: I92aa47d073a2038c5ac71fafbe8093ba4fee0e42
Signed-off-by: Humberto Borba <humberos@omnirom.org>

sony: common: Start sensors service later

---

rootdir/vendor/etc/init/adsprpcd.rc
rootdir/vendor/etc/init/hw/init.common.rc
rootdir/vendor/etc/init/sensors.rc

Like sensors service, adsprpcd is also intermittent
on suzu@loire due to some race condition at services initialization.
So this patch is moving adsprpcd service from main class to late_start
and also adding a property condition for its initialization.
on property:sys.qcom.devup=1
Now adsprpcd service starts with no problem.

[master] sony: common: Start adsprpcd service later

---

hardware/liblights/Android.mk
hardware/liblights/Light.h

On the DRM SDE driver, the display backlight is registered as a
backlight class device, hence it resides in a different folder.
Add a build variable TARGET_USES_SDE to switch the backlight
paths for the new driver.

[COMMON] hardware: lights: Add compatibility with DRM SDE driver

---

hardware/healthd/Android.mk
hardware/healthd/healthd_board_sony.cpp

extend commit 5fc2b506ce533aa537f76bac6bcde6b791a9ab26 to healthd.sony

healthd: Add compatibility with DRM SDE driver

---

manifest.xml

09-27 08:59:47.150   543   543 W /system/bin/hwservicemanager: getTransport: Cannot find entry android.hardware.renderscript@1.0::IDevice/default in either framework or device manifest.

manifest: add missing interface for renderscript

---

common-prop.mk
overlay/frameworks/base/core/res/res/values/config.xml

The feature is not working, and causes logcat spam by incessently trying to initialize wifi p2p, which is failing.
Disable it for now, until a solution is found.

[TEMP] common: disable wireless display

---

common-prop.mk

Devices that have broadcom bluetooth need the old property.
Since it has no effect on newer devices with qcom bluetooth, avoid adding a guard and simply include for all devices.

property: add back old BT address property

---

config.fs

The cnss-daemon needs to have AID_BLUETOOTH to be
able to be started from Android init.

[COMMON] config.fs: Assign bluetooth user/group to cnss-daemon

---

hardware/qcom/Android.mk

This patch allows custom android projects to use their ways to manage qcom hals location and its revision. Also, it will reduce deltas for custom projects which uses this project as an upstream.
Change-Id: I23f37e990641971d771ad8bcb3e72907ddded6cc
Signed-off-by: Humberto Borba <humberos@omnirom.org>

[master] sony: common: Allow custom projects to set their qcom hals

---

hardware/gpt-utils/gpt-utils.h

gpt-utils: add dtbo and vbmeta to partition swap list

---

rootdir/vendor/bin/init.qcom.devstart.sh
rootdir/vendor/etc/init/adsprpcd.rc
rootdir/vendor/etc/init/sensors.rc
rootdir/vendor/etc/init/sscrpcd.rc

Starting from Oreo, this should be a vendor property.
Needs a change in device-sony-sepolicy as well:
```
property_contexts:
vendor.qcom.devup          u:object_r:vendor_device_prop:s0
property.te:
type vendor_device_prop, property_type;
```

common: switch qcom.devup to vendor property

---

rootdir/vendor/etc/init/hw/init.common.rc

init: Drop /(vendor/)dsp restorecon and remount
Since we are now using stock labels(adsprpcd_file) and remounting a partition under /(system/)vendor is a neverallow in sepolicy anyway, drop the remount and restorecon.
init.rc: Update persist mountpoint
/persist has moved to /mnt/vendor/persist. Update init to reflect that.
N.b.: /vendor/dsp needs to be changed to read-only in the platform fstab files, change incoming.
https://github.com/sonyxperiadev/device-sony-tone/blob/a225e85d32a2574d6efe656f03a1ee0297851850/rootdir/vendor/etc/fstab.tone#L12

common init: Drop /dsp restorecon+remount, update persist mountpoint

---

Android.mk
common.mk
hardware/Android.mk
hardware/adreno/Android.mk
hardware/camera/Android.mk
hardware/firmware/Android.mk
hardware/qca_cld3/Android.mk
hardware/tftp/Android.mk
misc/Android.mk
misc/no-op/Android.mk
misc/version/Android.mk
sony_build_symlinks.mk
sony_clear_vars.mk

Fixes https://github.com/sonyxperiadev/bug_tracker/issues/253, should fix https://github.com/sonyxperiadev/bug_tracker/issues/283 as well.
Symlink creation is moved to it's own module to make sure these are executed during the build, not during module discovery. The amount of code has been reduced with loops and variables at the same time.
In the future we might be able to declare a build rule for every library (preferrably not a `foreach` that emits a module for all) to let the build system selectively regenerate the links.
Test:
1. `m installclean` followed by `m vendorimage` on current HEAD
2. Save all vendor links to a file: `find out/target/product/akatsuki/vendor -type l -exec echo -n {}" -> " \; -exec readlink {} \; | sort -u`
3. Check out this PR and run the commands from 1. …

Move vendor symlink creation to modules

---

Android.mk
common.mk
hardware/Android.mk
hardware/adreno/Android.mk
hardware/camera/Android.mk
hardware/qca_cld3/Android.mk
hardware/tftp/Android.mk
misc/Android.mk
misc/no-op/Android.mk
misc/version/Android.mk
sony_build_symlinks.mk
sony_clear_vars.mk

Backported from https://github.com/sonyxperiadev/device-sony-common/pull/552
Build-tested, but not compared because I don't have a clean 8.1 build anymore. @jamuir Since you asked for the backport, could you run `find out/target/product/<devicename>/vendor -type l -exec echo -n {}" -> " \; -exec readlink {} \; | sort -u >original_symlinks` prior to pulling and rebuilding (`m installclean` is enough)? Preferably on an sdm845 device to test `camera_symlinks`.

[backport][o-mr1] Adreno symlinks

---

common-prop.mk

dsds targets have own ro.telephony.default_network that one from common is not needed to copy in build.prop

allow override default_network common prop on dsds

---

common-prop.mk

The property helps identify the version solely through getprop.
This is helpful for when multiple versions can be found in a build, but only one actually used.

common-prop: add property for keymaster version

---

rootdir/vendor/etc/init/hw/init.common.rc

These permissions are needed to allow (for example) Extended Settings to
change PCC profiles on SDE-enabled devices.

init.common.rc: Permissions for dsi_panel_driver on SDE devices.

---

hardware/liblights/Light.cpp
hardware/liblights/Light.h

Android provides on- and off-times in `LightState` when requesting LED flash (for notifications). Because our default timings (set in dt) are rather short and appear trippy, adhere to the framework-orchestrated timings which are more forgiving 
TODO:
- Create and merge PR's to allow access to these new files. I'll get them up soon.
- This assumes all rgbsync (those with `/sys/class/leds/rgb/rgb_blink`) have these pause properties available. Please confirm that before merging.
I have not seen this property on Suzu, which doesn't have rgbsync either. Those platforms should stay unharmed.
- Test *without* the last commit. Scaling rgb channels with the `brightness` attribute is more efficient than scaling and applying the entire `duty_pcts` curve, but doesn't seem to work on akatsuki at least …

Adapt LED flashing time to android-dictated pause-times

---

hardware/adreno/Android.mk

For vendor v5, the file was renamed from `vulkan.$platform.so` to `vulkan.qcom.so`.

[DONOTMERGE] adreno symlinks: Update vulkan lib name

---

hardware/health/android.hardware.health@2.0-service.sony.rc

If permissions aren't set, the HAL will be unable to store
the measured battery capacity, hence raising the risk of
battery swelling due to extended wear.
PR solves the following message:
01-29 22:24:23.574   508   508 E /vendor/bin/hw/android.hardware.health@2.0-service.sony: Write max battery capacity to sysfs error: Permission denied
After solving the issue, the parameter is getting set as per this example:
01-29 22:26:19.978   508   508 I /vendor/bin/hw/android.hardware.health@2.0-service.sony: Successfully restored max battery capacity of 2456 mAh

[COMMON] hw: health: Fix permissions for battery_charge_full

---

common-treble.mk

These are just interface definitions which are used to compile various
modules. The generated helper libs contain boilerplate code to convert
from function calls to binder parcels and back. These are already
depended upon explicitly by the services themselves and thus included in
the final build.
Since there's no point in depending on these again (only to add
confusion and mix versions), drop all the lines.
EDIT: This is a continuation of #557, with more libraries dropped and a different commit description. Thanks @ix5 for pointing me to these dangling dependencies.

common-treble: Drop unnecessary wifi, fingerprint and radio interface inclusions.

---

common-perm.mk

- Use `TARGET_COPY_OUT_SYSTEM` instead of "system" so system-as-root targets won't have issues later on
- Copy vendor app perms to vendor: ExtendedSettings and TransPower are vendor apps now, so copy the accompanying priv-app permission xml files to `TARGET_COPY_OUT_VENDOR`

[DONOTMERGE] Adjust permission xml files target location

---

common-packages.mk
common-treble.mk

* Since we are providing our own service and
power.$(TARGET_DEVICE) is dead there's no
reason to build it.

Drop android.hardware.power@1.0 service and impl

---

hardware/power/Hints.cpp
hardware/power/android.hardware.power@1.3-service.sony.rc
hardware/power/common.h

Use init.rc mechanisms in order to create the powerhal socket folder `/dev/socket/powerhal` with the correct permissions and SELinux context. (Else the socket is created as `u:object_r:socket_device`!)
The new naming scheme is customary now

Powerhal fixes

---

overlay/frameworks/base/core/res/res/values/config.xml

* None of our devices support it.

overlay: Don't advertise SIM hotswap support

---

hardware/liblights/android.hardware.light@2.0-service.sony.rc
rootdir/Android.mk
rootdir/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc
rootdir/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc
rootdir/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc
rootdir/vendor/etc/init/hw/init.common.rc
rootdir/vendor/etc/init/qmuxd.rc
rootdir/vendor/etc/init/qseecom.rc
rootdir/vendor/etc/init/rild2.rc

- Add `interface` information to services' `init.rc` files, allows for dynamic HALs and maybe more in Q
- Rename services to follow the `vendor.*` pattern as upstream does
- Remove unused `charger.rc` definition
Most of these changes bring our configs in line with crosshatch.
**Attention:** Test carefully whether some blob relies on the old naming scheme, e.g. for `qseecomd`.

init: Update vendor services

---

rootdir/vendor/etc/init/hw/init.common.rc

Setting swappiness to 100 makes us to use swap (in our case
ZRAM) too much, instead of our dear RAM: while this is sort of
okay, meaning that we are compressing pages way more often,
this is a handheld device on ARM64 and running on battery.
Swappiness set to 100 will increase the power usage for no real
reason, not to mention the impacts on the device's performance
due to the increased computational overhead, hence set it to 25
so that we definitely prefer using the system memory and, when
we're about to run out of it, way before OOM or LMK kicks in, we
compress our pages to try to squeeze more data in.
Only at this point it is worth it to trade some performance and
battery to provide an overall better user experience.

[COMMON] init: common: Reduce swappiness to 25

---

common-prop.mk

This is needed when switching to whitelisted "compatible" properties only.

[WIP] common-prop: Prefix "vendor." to rild.libpath

---

CommonConfig.mk
vintf/vendor.nxp.nfc.interfaces.xml

`INxpNfc` is a vendor extension that is supported by the HAL code in `hardware/nxp/*`.

vintf: Add vendor.nxp.INxpNfc HAL to manifest

---

rootdir/vendor/etc/init/ipacm.rc
vintf/manifest.xml

Hal definitions from https://android.googlesource.com/device/google/crosshatch/+/618a01fe100bd98902e59ee9447cae975d4ce3b4
We still have to adapt the HAL itself to build for properly for the respective platforms.

manifest: Add tetheroffload config and control hals.

---

common-prop.mk

The legacy prop is still needed for devices which cannot be made fully
"compatible"

common-prop: Add back rild.libpath

---

rootdir/vendor/etc/init/adb_tcp.rc

Needs change in ExtendedSettings to update from `adb.network.*` to `vendor.adb.network`.
(Original PR content was to rename per-proxy and also act on the renamed multisim prop)

[WIP] init: adb_tcp: Use "compatible" ES adb port prop

---

common.mk

The sepolicy compiles correctly for both non- and full-treble devices and the last hurdle - PeripheralManager - is fully binderized now.
Having only one configuration to build eases maintenance and reduces build errors that only occur when compiling with FULL_TREBLE (and thus split sepolicy).

[WIP] common: Force split sepolicy on all shippping APIs

---

rootdir/vendor/etc/public.libraries.txt

Android is unable to load these libraries from /odm.
Trying to symlink the libraries to /system does not help because of namespace restrictions.
Resort to adding the libraries to public.libraries.txt as means of allowing Android to load them.

rootdir: vendor: declare aptX encoders as public libraries

---

rootdir/vendor/etc/init/sensors.rc

Fix labels when coming from stock
Note: The `restorecon` in `hw/init.common.rc` may skip the persist folder since it only checks whether the sepolicy `file_contexts` file has changed and not the actual folder contents.

[WIP] sensors.rc: Add restorecon for /persist/sensors/

---

rootdir/vendor/etc/init/hw/init.common.rc
rootdir/vendor/etc/init/sensors.rc

**NOTE:** This a simpler alternative to https://github.com/sonyxperiadev/device-sony-common/pull/600
The `restorecon_recursive` directive in init is only applied if the `file_contexts` file changed between builds, but not necessarily if any file or folder inside `/mnt/vendor/persist/` has changed.
The restorecon code checks whether an xattr named `security.restorecon_last` contains a string that matches the current combined hashes of the SELinux context files and skips restoring labels
if there is a match, see https://android.googlesource.com/platform/external/selinux/+/refs/tags/android-9.0.0_r35/libselinux/src/android/android_platform.c#1546
Force wiping that xattr so that restorecon always runs since it's not very expensive (there are currently only about 50 files on /persist).
The …

[WIP] init: Force restorecon for /mnt/vendor/persist

---

rootdir/vendor/etc/init/per-service.rc

Following Qualcomm and Google, set this service to
real-time io priority to ensure that the commands will
get to the peripherals as soon as possible (in real-time).
Sources
SDM845: https://source.codeaurora.org/quic/la/platform/vendor/qcom/skunk/tree/init.target.rc?h=LA.UM.7.3.r1-07400-sdm845.0#n156
SDM710: https://source.codeaurora.org/quic/la/platform/vendor/qcom/skunk/tree/init.target.rc?h=LA.UM.7.8.r4-00800-SDM710.0#n156
SDM660: https://source.codeaurora.org/quic/la/platform/vendor/qcom/falcon_64/tree/init.target.rc?h=LA.UM.7.6.2.r1-08500-89xx.0#n116
Google: https://android.googlesource.com/device/google/bonito/+/refs/heads/master/init.hardware.rc#476

[COMMON] init: per-service: Set pm-service to real-time ioprio

---

rootdir/vendor/etc/init/sensors.rc

The builtin init `chown` is not recursive, so individual filenames need to be supplied.
Fixes: `sensors.qcom` and `android.frameworks.sensorservice` cannot start up due to files in `/persist/sensors` being owned by `root:root`.

sensors.rc: Explicitly chown /persist/sensors

---

hardware/health/CycleCountBackupRestore.cpp
hardware/health/CycleCountBackupRestore.h
hardware/health/LearnedCapacityBackupRestore.cpp
hardware/health/LearnedCapacityBackupRestore.h

Major derp, the `cycles` arg to `::Read()` was discarded instead of updated.
Update from `int` to `int &` to make the health HAL actually store battery cycles.
Only check values on every 8th call, saving some read/writes.

Health HAL: Actually save read battery cycles, rate-limit LearnedCapacity backup

---

CommonConfig.mk
common.mk

The `PRODUCT_VENDOR_KERNEL_HEADERS` buildvar in [common-headers/KernelHeaders](https://github.com/sonyxperiadev/device-sony-common-headers/blob/aosp/LE.UM.2.3.2.r1.4/KernelHeaders.mk) depends on `KERNEL_PATH` and needs to be set early because it will have been set read-only when `CommonConfig.mk` is read.

[Q-COMPAT] Move kernel includes to common.mk

---

rootdir/vendor/etc/init/adspstart.rc
rootdir/vendor/etc/init/cdsprpcd.rc
rootdir/vendor/etc/init/cdspstart.rc
rootdir/vendor/etc/init/hw/init.common.rc
rootdir/vendor/etc/init/sensors.rc
rootdir/vendor/etc/init/slpistart.rc
rootdir/vendor/etc/init/sscrpcd.rc

init: Boot DSP before SLPI again
Before 8792c97, adsp and cdsp were booted before slpi:
init.qcom.devstart.sh
echo 1 > /sys/kernel/boot_adsp/boot
echo 1 > /sys/kernel/boot_cdsp/boot
echo 1 > /sys/kernel/boot_slpi/boot
8792c97 changed that behaviour to first booting SLPI via `init.qcom.devstart.sh`, setting `vendor.qcom.devup=1` and only then booting ADSP/CSDP via `init.qcom.(adsp|cdsp)start.sh`.
That and later commits caused race conditions that meant audio was gone on tone devices every other boot.
This commit restores the old behaviour of first booting ADSP/CDSP and then SLPI.

init: Boot DSP before SLPI again

---

rootdir/vendor/etc/init/adsprpcd.rc

This fixes the issue of the first boot on `forceencrypt` taking down `adsprpcd` without starting it back up again.
```
init    : processing action (vold.decrypt=trigger_shutdown_framework) from (/init.rc:715)
init    : Service 'vendor.adsprpcd' (pid 592) received signal 9
```
See: https://android.googlesource.com/platform/system/core/+/refs/tags/android-9.0.0_r39/rootdir/init.rc#716
`class main` brings it in sync with `cdsprpcd`, which is also in that class.
We can put it into `main` because the adsp and slpi devices will have been and remain booted already when the `vold.decrypt=trigger_shutdown_framework` prop triggers, no need to wait until `late_start` to start the `adsprpcd` service back up again.
btw... TOLD YA! :)

init: Enable adsprpcd instead of starting

---

rootdir/vendor/etc/init/hw/init.common.rc

Just like clearpads' glove attribute.
For https://github.com/sonyxperiadev/packages_apps_ExtendedSettings/pull/49.

[2/4] init: Allow system to access lge_touch/glove_mode in sysfs.

---

common-prop.mk

FBE CE switched from PBKDF2 to scrypt and scrypt's parameters are defined by 𝑁:𝑟:𝑝. However, in
Android we don't set 𝑁 directly. Instead, we set it via log(𝑁, 2) in the ro.crypto.scrypt_params
property whereby setting ro.crypto.scrypt_params=16:3:1 (AOSP's current default) would give a value
of 𝑁=65536. Google considered 𝑁=8192 as optimal for marlin, due to memory and CPU usage scaling
linearly with 𝑁, however this also would affect security negatively. Use a value of 15 (suggested
by Golang's increase in 2018) which is still less than AOSP's default but also provides a
performance boost while maintaining decent security.
For the reasoning on why AOSP have made sure 𝑁 is to be a power of two, this is due to random
selection one of the 𝑁 memory slots at each iteration - converting the hash …

common-prop: reduce cost of scrypt for FBE CE

---

CommonConfig.mk

The kernel recently got VDSO32 support and it now requires us
to compile kernel code targeting ARM/AArch32 (the VDSO32 compat
code does actually target 32-bits...) to get the feature to work.
Define the 32-bits toolchain to use to compile the VDSO32 in kernel.

[COMMON] CommonConfig: Add 32-bits toolchain prefix for VDSO32

---

common.mk

Move all vendor props into `(/system)/vendor/build.prop`
Mainly for treble compliance but also to declutter the platform repos that already define this.
This buildvar can be set for all devices, it just doesn't change that much for older devices without a phsyical `/vendor` partition.

common.mk: Force split props for all devices

---

hardware/power/Hints.cpp
hardware/power/android.hardware.power@1.3-service.sony.rc

Android's servicemanager somehow still wants to start @1.0 at boot, so annotate that version as well.
Tested on Q/master, please confirm on P.
(Also sneak in the removal of the unused `st` var in `Hints.cpp`)

[Q-COMPAT] Power: Add interface info to .rc

---

rootdir/vendor/etc/init/hw/init.common.rc

Entering the `vendor_init` context from other entrypoints is disallowed on Android Q, see:
https://android.googlesource.com/platform/system/sepolicy/+/44328c061d67636d4d8047ac69c4e778467eb4e8/public/vendor_init.te#263
`restorecon` now looks for the `security.sehash` xattr.
See https://android-review.googlesource.com/c/platform/external/selinux/+/916356
---
See https://github.com/sonyxperiadev/device-sony-sepolicy/pull/526 for updated sepolicy

[Q-COMPAT] Change toybox run context, update selinux xattr

---

hardware/gpt-utils/gpt-utils.cpp

After writing the contents to disk (such as marking a boot slot as
successful), we should additionally do an fsync() to make sure we commit
this information to disk before returning.
Bug: 131176531
Change-Id: I40c74bc8a39e4b32408bd73ecbdfd54eb8da957b
(cherry picked from commit d518ce7c6d3c2e3740da1269dfa8830d46fe5bd1)

gpt-utils: Add fsync() in gpt_disk_commit()

---

CommonConfig.mk
common-treble.mk

This will generate DRM plugins, HALs & oemcrypto_test in 64 bit.
Change-Id: I451db39edea3446d9816fcaba77caa8d3b097afb

sony-common: Enable 64 bit DRM plugins compilation

---

hardware/camera/Android.mk

sdm845 doesn't need the sm8150 link, and vice-versa.

hardware: camera: Only create library symlink for the relevant platform.

---

CommonConfig.mk
common.mk

`PRODUCT_` variables must be defined within the product chain
(`inherit-product`, starting with files defined in `PRODUCT_MAKEFILES`).
Outside of this chain, the variable is readonly:
> device/sony/common/CommonConfig.mk:114: error: cannot assign to readonly variable: PRODUCT_DEXPREOPT_SPEED_APPS

Move PRODUCT_DEXPREOPT_SPEED_APPS to common.mk.

---

vintf/android.hw.keymaster_v3.xml
vintf/android.hw.keymaster_v4.xml
vintf/android.hw.radio_ds.xml
vintf/android.hw.radio_ss.xml
vintf/manifest.xml
vintf/vendor.hw.radio_ds.xml
vintf/vendor.hw.radio_ss.xml
vintf/vendor.nxp.nfc.interfaces.xml

We are already qualifying for level 3 which is the compatibility_matrix released with Android Pie.
Aside, remove superfluous `target-level` defines in the other manifest files.
Tested on Mermaid+Discovery on Android 10 (Q), and on Discovery on Android 9 (Pie).
For completeness, please do a quick test locally on your device of choice on Android 9 to be extra sure.

Bump vintf manifest target-level to 3

---

rootdir/vendor/etc/init/wpa_supplicant.rc
vintf/manifest.xml

Tested on tama, kernel 4.9, **Android-10.0.0_r3**.
After checking log, I found this:
`10-01 08:23:02.928  1140  1420 E SupplicantStaIfaceHal: Method getKeyMgmtCapabilities is not supported in existing HAL`
and
`10-01 08:23:02.989   575   575 I hwservicemanager: getTransport: Cannot find entry android.hardware.wifi.hostapd@1.1::IHostapd/default in either framework or device manifest.`
`10-01 08:23:02.928   575   575 I hwservicemanager: getTransport: Cannot find entry android.hardware.wifi.supplicant@1.2::ISupplicant/default in either framework or device`
We need to upgrade the wifi hal to support Q. Code from [Google](https://android.googlesource.com/platform/frameworks/opt/net/wifi/+/master/service/java/com/android/server/wifi/SupplicantStaIfaceHal.java#3102).

common: Upgrade wifi hal version

---

common.mk

This is needed to get OTA packaging to work since Android Q since certain OTA parameters are extracted from an intermediate recovery image. Don't as why...
On Pie, a recovery image is built by default anyway, so this commit changes nothing on Pie.
Relavant: https://r.android.com/951796
Changing:
```
ifeq (,$(filter true, $(TARGET_NO_KERNEL) $(TARGET_NO_RECOVERY)))
[... build recoveryimage]
```
to:
```
ifeq ($(BOARD_USES_RECOVERY_AS_BOOT),true)
BUILDING_RECOVERY_IMAGE := true
else ifeq ($(PRODUCT_BUILD_RECOVERY_IMAGE),)
ifdef BOARD_RECOVERYIMAGE_PARTITION_SIZE
ifeq (,$(filter true, $(TARGET_NO_KERNEL) $(TARGET_NO_RECOVERY)))
BUILDING_RECOVERY_IMAGE := true
endif
endif
else ifeq ($(PRODUCT_BUILD_RECOVERY_IMAGE),true)
BUILDING_RECOVERY_IMAGE := true
endif
[... build recoveryimage]
```
--- …

[Q-COMPAT] common: Set PRODUCT_BUILD_RECOVERY_IMAGE=true

---

vintf/manifest.xml

All work fine on both 1.2 and 1.3, we update it for more new features

vintf: Upgrade wifi hal to 1.3

---

common-treble.mk
vintf/manifest.xml

The widevine service is proprietary and not shipped with AOSP.
Declaring it in the `vintf` manifest will result in an endless loop of `servicemanager` trying to start the service.
Downstream projects are advised to revert this commit if they are shipping the widevine blobs.

common-treble/vintf: Remove widevine refs

---

common-treble.mk
rootdir/Android.mk
rootdir/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc
rootdir/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc

These blobs only provide a passthrough service for the implementations
stored in the shared libraries. AOSP provides an identical solution
complete with .rc files and "OSS code" (not that there's anything to see
apart registering a default passthrough implementation).
See
https://github.com/sonyxperiadev/device-sony-common/pull/617#issuecomment-536089919
for an expanded explanation.

[1/2] common: Replace gatekeeper/keymaster passthrough blobs with AOSP variant

---

common.mk

For example SystemUI didn't show up despite the name being correct.
Instead of trying to collect all currently overriden targets, and not
forgetting to add them in the future, follow crosshatch and build _any_
overlay as RRO. This is the most compatible with GSIs.

common: Enforce all overlays to be a separate RRO on /vendor.

---

hardware/gpt-utils/gpt-utils.cpp

This PR fixes the issue of getting the correct device name in Sailfish. In contrast to AOSP, Sailfish populates /dev with relative and not absolute links. As a result, current `get_dev_path_from_partition_name` was failing. This implementation gets a symlink, de-references it, and then guesses device name on the basis of de-referencing result.
I have tested earlier version on Sailfish for some time now and it works as expected. I have not tested on AOSP, though. The last version has `for` loop replaced by `while` - haven't tested that on device yet. But its expected to be equivalent to the tested one.
Acknowledgements: Basic idea is coming from Adam Pigg implementation for one of Sailfish ports, implementation discussed with Marijn

gpt-utils: dereference symlinks pointing to device path

---

hardware/power/power-helper.c

On kernel 4.14 the power stats for WLAN is in sysfs instead.

PowerHAL: power-helper: Fix WLAN STATS file path for k4.14

---

hardware/liblights/Android.mk
hardware/liblights/Light.cpp
hardware/liblights/Light.h
hardware/liblights/service.cpp

This change fixes a slight mistake that was introduced when trying to
improve accuracy.
https://github.com/sonyxperiadev/device-sony-common/commit/6199c66e80d7538c8f6633b742d83679e6bbf2a4
That patch aims to ensure maximum brightness is reached - which indeed
happens for value 0xff - but adds a small discrepancy as outlined below.
Consider the following example:
```python3
bits = 10
sbits = bits - 8
maxval = (1 << bits) - 1
for brightness in range(256):
print(f'{brightness} => '
f'original: {brightness << sbits | brightness >> sbits}, '
f'proper: {round(brightness * maxval / 255)}, '
f'fixed: {brightness << sbits | brightness >> (8 - sbits)}')
```
When running the example (see output below) a consistent (yet small)
bump can be observed because the highest bits are replicated in the
lower …

lights: Adjust slightly off brightness conversion for maximum accuracy.

---

hardware/liblights/Light.cpp
hardware/liblights/Light.h

The RGB tri-led now uses a different driver combo (pwm+led)
and it uses the Linux standard LED triggers... with different
paths.
Make a basic conversion of this HAL so that we get the very
basic functionality out of it.
Advanced functionality such as heartbeat and other triggers
can be implemented later.

[COMMON] liblights: Migrate to kernel 4.14 LED class for RGB tri-led

---

common-perm.mk
rootdir/vendor/etc/permissions/enable_deprecated_beam.xml

This feature is not gone yet, but it's going. Enable it for our devices
instead of cutting ourselves off from a file tranfering and sharing
feature that pretty much 99% of the other Android smartphones still
have.
See https://r.android.com/848931 for more details.

permissions: Re-enable deprecated Android Beam on Android 10.

---

CommonConfig.mk

Android 10 seems to now recommend (and it does support) kernel memory
accounting and on kernel 4.14 it's possible to use this just fine.
Tested on SoMC Tama Akari DSDS.

[COMMON] Enable memcg for Android 10

---

CommonConfig.mk

Google added a new property ro.vendor.build.security_patch that's not
set to any sensible value by default. Our kew keymaster implementations
(KM4 on kernel 4.14 for the time being) rely on this value for rollback
protection.
Set it to the same value as the system currently built.
@ix5 Do you have any comment on this? Seems the only sensible default to me, no idea why AOSP doesn't set it.

CommonConfig: Set VENDOR_SECURITY_PATCH for new Keymasters.

---

common.mk

ffcd156e7997de9917cab0284f20ea357bafb5a0 added the module, now actually include it.
The symlink `/vendor/lib/rfsa` -> `/odm/lib/rfsa` is needed for the new k4.14 blobs.

common: Add rfsa_symlinks package

---

CommonConfig.mk

Android 10's build system will fail to build the kernel if we use these
prefixes due to "unallowed paths".

[COMMON] [URGENT] CommonConfig: Remove kernel cross compile prefixes for Q

---

common-treble.mk

Kumano uses a different vibrator HAL, and leaving the default
implementation at V1.0 in the build results in a mess.
Make sure only one of the two services is built and included in the
image.
To simplify and prepare for future platforms most likely using the same
or a similar HAL, move the inclusion of vendor.qti.hardware.vibrator
here as well, instead of leaving it in kumano/platform.mk.

[1/2] common-treble: Build vibrator 1.0 or 1.2 based on TARGET_VIBRATOR_V1_2.

---

common-prop.mk

These properties are required to stop some issues, like tearing and
lines of corruption on single-surface rendering, while using the device
on Android vendor based on kernel 4.14 BSPs.

[COMMON] [URGENT] common-prop: Add common necessary display properties

---

rootdir/vendor/etc/init/ipacm.rc
vintf/manifest.xml

These interfaces are hosted by `ipacm`. Add the interfaces to the vintf (which is enforcing in our builds) and list them in the initrc.
This PR has originally been merged and accidentally force-pushed off for another feature:
https://github.com/sonyxperiadev/device-sony-common/pull/556

[COMMON] Add tetheroffload HIDL interfaces

---

CommonConfig.mk
overlay/frameworks/base/core/res/res/values/config.xml

https://source.android.com/devices/tech/connect/wifi-sta-ap-concurrency
All our platforms support concurrent STA/AP (see output of `iw info`), including Loire and Tone on brcmfmac (which have recently been dropped from these master branches).
Platforms on QCACLD require an extra flag `gEnableConcurrentSTA=wlan1` in `WCNSS_qcom_cfg.ini` which will be PR'ed separately to platform repositories: this flag creates an `__ap` interface named `wlan1`. Loire and Tone require a manual command to create this interface which can be provided and backported to the appropriate tags if desired.
There is one configuration option that does not make a lot of sense, but is enabled on crosshatch and coral: https://android.googlesource.com/device/google/crosshatch/+/9e44fc78629b66c93d6dc6d78f98245853a0c1f8%5E%2 …

[COMMON] Enable WiFi concurrent STA/AP for all platforms

---

hardware/qcom/Android.mk

A wild vidc_3x port from kernel 4.9 to 4.14 has appeared and we want to
use it in place of a huge rework of both HAL and SM8150 vidc driver
for all the legacy SoCs.
Place the new libion ported HAL in hardware/qcom/media/sdm660-libion
and use it for SoC range msm8956-sdm660.
The SDM845 SoC is kept on the new SM8150 codebase, as it is
compatible with only minor changes.

[COMMON] Switch to dual media HAL again for legacy SoC

---

common-prop.mk

This prop allow to prefer HW codecs on top of SW for thumbnails, saving battery, getting faster decoding and still having a fallback in case HW codecs are broken.

common-prop : Add Stagefright prop

---

common.mk

Since all devices are now fully treble compatible, we can enable `PRODUCT_FULL_TREBLE_OVERRIDE`.
`PRODUCT_FULL_TREBLE_OVERRIDE` sets:
- `PRODUCT_TREBLE_LINKER_NAMESPACES`
- `PRODUCT_SEPOLICY_SPLIT`
- `PRODUCT_ENFORCE_VINTF_MANIFEST`
- `PRODUCT_NOTICE_SPLIT`
And also `BOARD_PROPERTY_OVERRIDES_SPLIT_ENABLED` indirectly.
Setting `PRODUCT_USE_VNDK_OVERRIDE` is still needed because `PRODUCT_USE_VNDK` will only be set based on `PRODUCT_FULL_TREBLE` if the shipping API level is 27 or greater.
Also add `vndk_package` in common so that devices don't need to add it individually.
We might get rid of these vars entirely by inheriting products from `build/make/product/` at a later date.

[WIP] common: Simplify treble buildvars, add VNDK pkg

---

rootdir/init.recovery.common.rc

Refresh the USB configuration in order to get ADB sideloading
back up.
TEST:
SoMC Tama Akatsuki: ADB sideload working, USB composition switch OK (Recovery)

[COMMON] init.recovery: Refresh recovery USB configuration for k4.14 Android 10

---

common-init.mk
rootdir/Android.mk
rootdir/vendor/etc/init/dpmQmiMgr.rc

This service is required on Kumano.

common-init: add dpmQmiMgr service file.

---

rootdir/vendor/etc/sec_config

On k4.14 BSPs we have new allowances required for new QMI
services present in there.

[COMMON][ vendor: sec_config: Add missing allowances for 4.14

---

CommonConfig.mk

On Android 10 we need more loopback partitions in order
to get APEX working as per design.

[COMMON] CommonConfig: Raise maximum possible loopback partitions

---

common-treble.mk
vintf/manifest.xml

DONOTMERGE: Composer 2.3 _depends on_ 8.1 display. It'll _crash_ with 7.1, likely due to missing/unimplemented/broken functionality.
After moving to CAF 8.1 display branches the new composer can and should
be used.

treble/vintf: Bump graphics.composer to version 2.3.

---

CommonConfig.mk
vintf/android.hardware.radio.config.xml
vintf/vendor.hw.radio_ds.xml
vintf/vendor.hw.radio_ss.xml

Set the right versions for IImsRadio and IUim for the new qcrild.
Also add the IRadioConfig 1.1 to stop complains.

[COMMON] Set right versions for IMS/UIM, add IRadioConfig

---

CommonConfig.mk
vintf/vendor.hw.radio.uceservice.xml

This interface is necessary in order to successfully register IMS
services.

[COMMON] CommonConfig/vintf: Add QTI IUceService 2.1 for IMS

---

common.mk

This resolves two subtle issues with the inherit-product mechanism:
- Inherited files are evaluated later, at least after _common.mk_ has
been fully read despite the call to inherit-product being at the top
of the file;
- The ordering between other inherit-product calls is not guaranteed;
the list is sorted to remove duplicates and provide consistency.
The observed problem at hand is overriding TARGET_USE_QCRILD in
customization.mk, as is happening in PE. Due to sorting common-init.mk
(which uses this variable) is evaluated _before_ customization.mk,
leading to the wrong rc files ending up on vendor.img.
CommonConfig.mk on the other hand is parsed after the entire product
inheritance tree is evaluated, hence the right vintf is selected
according to this variable.
This issue is fixed by …

common: Forcibly include customization.mk at the beginning of common.mk

---

common-init.mk
rootdir/Android.mk
rootdir/vendor/bin/init.qcom.modem.sh
rootdir/vendor/etc/init/init.modem.rc

This script will copy the modem operator configurations to the
right folders for consumption by the RIL.
This ensures correct modem operation on all of the (supported)
carriers requiring special mcfg_sw configurations.

[COMMON] vendor: Add startup modem operator configuration scripts

---

overlay/frameworks/base/core/res/res/values/config.xml
overlay/packages/services/Telephony/res/values/config.xml

This patchset allows to get proper support for the IMS features in the frameworks.
Also brings faster Emergency PDN attachment when home network is not available
and SIM is inserted in order to start the call in less time... and speeds up the first
home network attachment procedure (at boot, or after airplane mode cycle).

[COMMON] Proper support for IMS, faster emergency, faster network attachment

---

rootdir/init.recovery.common.rc

This gives issues with Kumano: removing it brings it to
functional adb shell in recovery.
Tested on SoMC SM8150 Kumano Bahamut DSDS

[COMMON] init.recovery: Remove paranoid ADB configuration

---

common-init.mk
rootdir/Android.mk
rootdir/vendor/etc/init/adsprpcd.rc
rootdir/vendor/etc/init/audiopd.rc

Guard the separated service with a flag instead of enabling at boot time via prop.

rootdir: vendor: move audiopd to own file

---

common-packages.mk
common.mk

For https://github.com/sonyxperiadev/vendor-qcom-opensource-core-utils/pull/2
This namespace contains the necessary libqti_vndfwk_detect.

common: Include vendor/qcom/opensource/core-utils Soong namespace.

---

CommonConfig.mk
common.mk

Move the BOARD_PREBUILT_DTBOIMAGE var for the prebuilt kernel from the platform repos to common, declutters the platform repos.
For building the kernel in-tree:
Set BOARD_PREBUILT_DTBOIMAGE - guarded by BUILD_KERNEL - so that the `dtbo-$(DEVICE).img` file can have an AVB hash footer appended by the build system.
This declutters the platform repos
I borked that one in 7637020af0612d44493b78240d1a089c93b9be97 "[Android-10] Move kernel includes to common.mk".
Now the flag can be overriden in Customization.mk.
https://github.com/sonyxperiadev/device-sony-loire/pull/264
https://github.com/sonyxperiadev/device-sony-tone/pull/188
https://github.com/sonyxperiadev/device-sony-yoshino/pull/152
https://github.com/sonyxperiadev/device-sony-nile/pull/106 …

[1/3] Kernel rework

---

CommonConfig.mk
common.mk

Following changes of @ix5 to fix build in legacy devices.
Platform will need change in platform.mk. See [Loire for example](https://github.com/sonyxperiadev/device-sony-loire/commit/678af16ec3d2283e0a88da9130d623d60cffa6b2)
Should be merged together with [kernel/PR2216](https://github.com/sonyxperiadev/kernel/pull/2216)
I am currently testing this for Kugo/Loire. Other device/platform tests would be nice.

[q-mr1-legacy] Move kernel path to common config

---

rootdir/vendor/etc/init/sensors.rc

Fixes https://github.com/sonyxperiadev/bug_tracker/issues/515
> Sensors do not seem to depend on data files at all, only persist is
> (supposed to be) used. Aside from that starting the service this late
> (after the FDE decryption password has been entered) seems too late to
> get sensors working properly.
>
> This patch enables the service as soon as the dsp is up (devup=1) and
> moves the service to the core class to be started early and never
> restarted when /data is mounted. Furthermore enabling the service rather
> than explicitly starting it allows the service to be restarted in the
> event of a crash.
> 
> Aside from that folder creation is removed, which does not seem to be
> necessary.
>

[DONOTMERGE/PLEASEDISCUSS] sensors: Remove /data dependencies for earlier start

---

CommonConfig.mk
vintf/vendor.hw.imsservices.xml

These HALs are required in order to get IMS services up and
running.

[COMMON] vintf: Add IMS Services CallInfo and IMSRTPService HIDL

---

common-prop.mk

Until Pie, the `ConfigStore` HAL was supposed to configure `SurfaceFlinger`.
Google, in their infinite wisdom, got bored of this approach and decided that sysprops (which
ConfigStore was supposed to supplant, because of their _obvious drawbacks) were once again all the rage.
The ConfigStore HAL is being deprecated and will apparently be removed in R, see [the deprecation notice](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-10.0.0_r33/configstore/README.md).
Translate the uppercase makevars that [`surfaceflinger.mk`](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-10.0.0_r33/configstore/1.1/default/surfaceflinger.mk) used to supply as cflags to configstore internals to sysprops.
```
force_hwc_copy_for_virtual_displays = …
```

common-prop: Sync SurfaceFlinger props

---

common.mk

These files are necessary across all platforms to use the new bluetooth
audio HAL for registering and transfering audio to BT endpoints.
The files are used from updated policy configuration files in platform
repositories.

[COMMON] Include bluetooth.audio@2.0 policy configuration files

---

common-prop.mk

IMS needs some other properties to be set.... also, qcrild supports some nice
features, which are definitely supported on all platforms.
For more informations on what, how, when and why, refer to the
descriptions for each commit in this patchset.
Tested on SoMC Kumano Griffin DSDS

[COMMON] Configure modem properly on qcrild and for IMS

---

common-perm.mk
common-treble.mk

Bump up the NFC HIDL to 1.2 and add Host Card Emulation for FelicityCard,
since we support it anyway.

[COMMON] Bump up NFC to 1.2 and add HCE for FeliCa

---

common-packages.mk
common-treble.mk
common.mk
vintf/manifest.xml

@stefanhh0 I woke up realising that the new 5.0 policy was PR'd by me to legacy platforms:
https://github.com/sonyxperiadev/device-sony-loire/pull/266
https://github.com/sonyxperiadev/device-sony-tone/pull/193
... without updating the legacy common branch too.
Can you and the other Loire/Tone @ Android10 users validate that there is audio, both from speakers, wired and bluetooth headphones, as well as in calls and such?

[COMMON] [Q-LEGACY] Bump audio to 5.0, provide policy config

---

vintf/manifest.xml
vintf/vendor.nxp.nfc.interfaces.xml

We are shiping the 1.2 nxp nfc service now.
The vendor.nxp version was wrong, there is no @1.1 interface as of now.

vintf: Align NFC

---

rootdir/vendor/etc/init/init.usb.rc

This has been a no-op for a long time and will throw an error in Android R.
See https://android.googlesource.com/platform/system/core/+/refs/tags/android-10.0.0_r33/init/builtins.cpp#1056

[R] rootdir: usb.rc: Drop load_system_props

---

common-prop.mk

This enables legacy `libril` from legacy `rild` and `qcrild` to host the IQtiOemHook, required to implement TransPower for SAR compliance and some more features in the near future.

[COMMON] Enable IQtiOemHook

---

common-packages.mk
common-prop.mk

This is the first big part to enable IMS functionalities, including VoLTE,
VideoTelephony and Wi-Fi Calling, and other important power saving
and enhancements for mobile data connectivity, including:
- Connectivity Engine (CnE)
- DPM (Data Path Manager) with:
--- Fast Dormancy (FD)
--- TCP Connection Manager (TCM)
Note that there would be too many comments to do on this patchset,
so, if you want more informations about what's in the works, PLEASE,
refer to the commit messages of this patchset.
WARNING: This is PART 1. This is SAFE TO MERGE right now, but obviously
the functionalities will not work without the proper binaries.
Enjoy!

[COMMON] [PART1] VoLTE/VT/WFC + DPM/TCM/CnE enablement

---

CommonConfig.mk
common-init.mk
rootdir/Android.mk
rootdir/vendor/etc/init/adpl.rc
rootdir/vendor/etc/init/dataqti.rc
rootdir/vendor/etc/init/dpmd.rc
vintf/vendor.hw.dataservices.xml
vintf/vendor.hw.imsservices.xml
vintf/vendor.hw.radio_ds.xml
vintf/vendor.hw.radio_ss.xml

This is the PART2 patchset to allow loading the new VINTFs for IMS and
data services directly or indirectly required by it.
This PR is safe to merge, as these services are present in all ODM versions.

[COMMON] [PART2] Allow new data/radio VINTFs to load

---

CommonConfig.mk

Change := to += for DEVICE_MANIFEST_FILE and DEVICE_MATRIX_FILE
so that we are allowed to add manifest/matrix files from the external
customization repository, if present.

[COMMON] CommonConfig: Allow adding manifest/matrix from customization

---

hardware/qcom/Android.mk

Display, media and ipa hals are now automatically included by the build system.
Explictly including them leads to double module definitions.
Additionally, add a brief documentationfor QCOM_NEW_MEDIA_PLATFORM.

hw: qcom: do not explictly include hals

---

common-odm.mk

The ims-ext-common, qti-telephony-wrapper,
qti-telephony-common are open source
components, found in vendor-qcom-opensource-telephony.

[COMMON] [URGENT] common-odm: Remove OSS components

---

hardware/tftp/Android.mk

We should be trying to get rid of the rootfs `/firmware` and `/persist` compatibility symlinks.
That entails actually not using them any more...

[VERIFYME] tftp_symlinks: Use updated persist and fw targets

---

overlay/frameworks/base/core/res/res/values/config.xml
overlay/packages/apps/CarrierConfig/res/xml/vendor.xml

Google (again) moved the location of gps config.
This time they were kept in overlays, but instead of adding to frameworks/core, they are added to CarrierConfig

overlay: CarrierConfig: add GPS config

---

CommonConfig.mk
vintf/vendor.qualcomm.qti.dpm.xml

This new interface is hosted by dpmQmiMgr and used by dpmd.
See also https://github.com/sonyxperiadev/device-sony-sepolicy/pull/567 for the backing policy.
TODO: Is there a more sensible file to move this into?

[COMMON] vintf: Add com.qualcomm.qti.dpm.api::IdpmQmi@1.0

---

rootdir/Android.mk

The file is named dpmd.rc, as is the dependency on it in common-init.mk.
Fixes: fa14c9db6b4a6fd837eb771728e51cb7bc8eaa14
---
Another joker, just like https://github.com/sonyxperiadev/device-sony-common/pull/734 :)

rootdir: Fix dpmd module name

---

rootdir/Android.mk

Got lost in 35c3a0fea71f6c61ec81ea7989562ae8c1d8c954
"rootdir: Convert .mk to .bp"
Still needed because else Android's build system does not
automatically make paths relative to the file unless
LOCAL_PATH is called.

rootdir: Restore LOCAL_PATH call

---

CommonConfig.mk

See the PR to master for more details: https://github.com/sonyxperiadev/device-sony-common/pull/743
After fixing local projects using TZapps (fingerprint) and enabling
ueventd to read firmware directly from /vendor/firmware_mnt/image/ it is
now time to drop this unstable symlink and watch our devices... work
just as fine as before.
The problem with /firmware is that it resides in the root partition;
and may be missing entirely on system-as-root GSIs. Even if it exists
sepolicy may be conflicting, disallowing files from being loaded.
Instead all our firmware should be directly referenced in /odm or
/vendor.

[COMMON] [WIP] [Q-MR1] Drop legacy/unstable /firmware symlink

---

CommonConfig.mk
config.fs

Delete `config.fs` mappings for `/dsp` and `/firmware` which are not necessary/used anymore.
Also drop `/bt_firwmware` which is not stable (SAR GSIs...) and not necessary either, as the HAL falls back to `/vendor/bt_firmware` properly. Unfortunately not gracefully though; this has to happen with big red error lines for some reason.
E vendor.qti.bluetooth@1.0-patch_dl_manager: /bt_firmware/image/crbtfw21.tlv File Open Fail No such file or directory (2)
I vendor.qti.bluetooth@1.0-patch_dl_manager: File open /vendor/bt_firmware/image/crbtfw21.tlv succeeded
E vendor.qti.bluetooth@1.0-patch_dl_manager: /bt_firmware/image/crnv21.b00 File Open Fail No such file or directory (2)
E vendor.qti.bluetooth@1.0-patch_dl_manager: /vendor/bt_firmware/image/crnv21.b00 File Opening from alternate path: …

[COMMON] Remove /firmware and /dsp remnants, also drop /bt_firmware entirely

---

CommonConfig.mk
common-init.mk
rootdir/Android.bp
rootdir/vendor/etc/init/init.sony-modem-switcher.rc
rootdir/vendor/etc/init/vendor.somc.hardware.miscta@1.0-service.rc
rootdir/vendor/etc/init/vendor.somc.hardware.modemswitcher@1.0-service.rc
vintf/vendor.somc.modem.xml

These two services and a single binary make it possible to flash carrier-specific firmware, as found in `/vendor/firmware_mnt/image/modem_pr`. The configuration utility receives an `S###.#` value through `persist.somc.custom.modem#` which resolves to a firmware path by reading /oem/modem-config/S###.#/modem.config. If no mapping is found it defaults to the path stored in TA.
This property is set by our new `ModemConfig` application which takes care of listening for sim changes to compute the desired `S###.#` for the carrier.
Note that we should seek to get the services to look for `persist.vendor.` props in the near future, as well as a different folder containing modem files. Bind-mounting /oem isn't very convenient.
Sepolicy and the ModemConfig app will follow tomorrow.

[COMMON] Add init and vintf declarations for the modem switcher stack

---

common.mk
rootdir/vendor/etc/seccomp_policy/mediacodec.policy
rootdir/vendor/etc/seccomp_policy/mediaextractor.policy

These syscalls are now allowed by default.
[arco] Also clean mediacodec.policy
Change-Id: I405f609d030331e19031612cbd912a54a3c72339
---
Proof:
https://android.googlesource.com/platform/frameworks/av/+/refs/tags/android-10.0.0_r35/services/mediaextractor/seccomp_policy/mediaextractor-arm64.policy
`readlinkat`, `pread64` contained
https://android.googlesource.com/platform/frameworks/av/+/refs/tags/android-10.0.0_r35/services/mediacodec/seccomp_policy/mediacodec-arm.policy
`_llseek`, `getdents64` contained

rootdir: Drop mediaextractor seccomp policy

---

common-packages.mk

Our new modem configuration utility, that provokes sony-modem-switcher
to send carrier-specific firmware to the modem, is finally done :)

[COMMON] packages: Add ModemConfig

---

rootdir/Android.bp

Without "strip: none", Android's build system will try to optimize any cc_prebuilt_binary.
Since there's not much that llvm can do to further strip a plaintext script, instruct it to restrain itself.
Fixes:
```
prebuilts/clang/host/linux-x86/clang-r353983c1/bin/llvm-strip: \
error: 'device/sony/common/rootdir/vendor/bin/init.qcom.adspstart.sh': \
The file was not recognized as a valid object file
```

rootdir: Do not attempt to strip scripts

---

common-init.mk
common.mk
rootdir/Android.mk
rootdir/vendor/etc/data/dsi_config.xml
rootdir/vendor/etc/data/netmgr_config.xml
rootdir/vendor/etc/gpfspath_oem_config.xml
rootdir/vendor/etc/init/hw/init.common.rc
rootdir/vendor/etc/init/sensorspd.rc

The ADSP on some targets have a Sensors PDR Service: add the
init script in order to enable the transport endpoint to the
tms/servreg service, located on sensors_pdr_adsprpc.
This init script gets copied when the target device declares
TARGET_NEEDS_SENSORS_PDR := true
EDIT:
Also, push netmgr/dsi config for SM6125 and add the QSEE
TZ Storage configuration and paths, required by new devices
and new BSPs. 
Required by new SoCs.

[COMMON] Additional configuration for new devices and new features

---

rootdir/vendor/etc/gpfspath_oem_config.xml

This whitelist (though it does not exclude but rather INCLUDE) moves all
paths starting with one of the entries into gp_data_path to solve system
boundary issues such as files in /data/{system,misc}, see our BUGS in
sepolicy for tee [1].
Unfortunately this breaks FPC (which is one such violation) in the
process:
[pid  8105] openat(AT_FDCWD, 0x77e677a004, O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
[pid  8105] openat(AT_FDCWD, "/data/vendor/tzstorage//data/system/users/0/fpdata/user.db.tmp", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
[pid  8105] openat(AT_FDCWD, "/data/vendor/tzstorage//data/system/users/0/fpdata/", O_RDONLY|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
[pid  8105] openat(AT_FDCWD, …

vendor: GP FS: Drop /data/system/users/ from whitelist

---

common-prop.mk

Correctly configure audio buffers, enc/decoders etc for optimizations
related to battery and latency.
Also solves a buffer underrun issue that happens rarely on legacy SoCs
but rather commonly on newer ones, like SM8150: this solution was
previously applied only on device-sony-kumano, but it's actually applying
to all of the platforms that we currently supports.
Of course, a PR on device-sony-kumano will remove the duplication that
happens by merging this.

[COMMON] Audio related battery and latency optimizations

---

rootdir/vendor/etc/init/hw/init.common.rc

No need to wait until late-fs if `/vendor` is already available after `mount_all --early` has run.

rootdir: init.common: Bindmount /oem earlier

---

rootdir/vendor/etc/init/hw/init.common.rc

FDE devices experience race conditions because `/data` might not be available for the services started `on late-fs`.
Rather, delay until `/data` is mounted.
Tested on Kagura with `forceencrypt=footer` in fstab, and "Secure Startup"
requiring PIN entry enabled.

init.common: Fix service start order for FDE

---

vintf/manifest.xml

In Android R, the android.hardware.usb@1.0-service module already ships its own `vintf_fragment` for `IUsb`.
Needs a change to the legacy "basic" USB HAL for users of `BOARD_USE_LEGACY_USB`.

[R] vintf: Remove usb, already defined

---

common-packages.mk
common.mk
rootdir/vendor/etc/public.libraries.txt

Our blobs are compiled against `libprotobuf-full-cpp.so`, but starting in R, Android is using a versioned naming approach, e.g. `libprotobuf-cpp-full-3.9.1.so`.
See https://r.android.com/1109518
The entry in `public.libraries.txt` is needed to allow the linker to find and use the lib outside the VNDK.
See https://source.android.com/devices/tech/config/namespaces_libraries

[R] packages: Add protobuf vendorcompat lib

---

common-init.mk
rootdir/Android.mk
rootdir/vendor/etc/init/adsp-sensorspdr.rc
rootdir/vendor/etc/init/sdsp-sensorspdr.rc
rootdir/vendor/etc/init/sensors.rc

The higher tier SoCs have got a dedicated Sensors Low Power Island
(SLPI) with its own RTOS: in this case the Sensors PDR is not
located on the ADSP, but on the SDSP (SSC).
For this reason, introduce a new init definition for the latter,
change it for the former, and activate it on these conditions:
1. TARGET_NEEDS_ADSP_SENSORS_PDR is *false*
2. TARGET_NEEDS_SDSP_SENSORS_PDR is *true*.
For obvious reasons, *no* target can have a Sensors PDR on both
A- and S- DSP... That's why one force-excludes the other.
Also, to avoid issues with having two of them together, trigger
a build error in case both env vars are true, so that the
developer is warned about the impossible *stupid*  choice.
--------
The PDR init is verified working on Sony SM8150 Kumano Griffin DSDS,
but I want some feedback from …

[COMMON] init: Introduce support for Sensors PDR on SDSP

---

common-prop.mk

Some platforms do support and *need* this feature: let's remove
the disablement from the common repo.
Solves issues with Kumano platform.

[COMMON] [URGENT] [Q-MR1] common: Remove disablement of compress input

---

CommonConfig.mk
common.mk

Yes, the new release is approaching and you know what that means: Groundhog Day!
Once again, Android is not respecting a make target in favour of some highfalutin new endeavour, this time "vendor_boot".
Set building `vendor_boot.img` to false and actually re-enable building of `boot.img` for non-`RECOVERY_AS_BOOT` devices when you `make bootimg`.

[R] Explicitly enable traditional boot.img

---

rootdir/vendor/etc/data/netmgr_config.xml

Enable the new data-kernel RMNET driver in kernel 4.14 by updating
the configuration for MSM8998 and SDM845.
Now this platform has to use the same driver as newer platforms.
Depends on:
https://github.com/sonyxperiadev/kernel-defconfig/pull/85
https://github.com/sonyxperiadev/kernel/pull/2321
Tested on TIM IT LTE network:
MSM8998 Yoshino Maple RoW - DL: 94Mbps UL: 28Mbps
SDM845 Tama Akatsuki RoW - DL: 118Mbps UL:27Mbps
P.S.: Tests on stock are showing basically the same numbers, between
margin of error, so my tests are being limited by the network.
In any case, it's a big improvement from the old tests, without this
changes, showing around 10MBits in both DL and UL at best!

[COMMON] [Q-MR1] vendor: data: netmgr: Update MSM8998, SDM845 config for new RMNET

---

common-prop.mk

Three of our platforms - Yoshino, Nile and Ganges - use this feature.
This is not only evident from the fact that CAF audio enables it on
sdm660 and msm8998, but the lack of `echo-reference-voip` mixer paths.
Only echo-reference is available, where `-voip` is appened if compr_voip
is disabled.
Explicitly enabling this feature (which defaults to false) in platform
repos fixes issues with calls that utilize echo-reference.

[COMMON] Remove forced disablement of compr_voip audio feature

---

rootdir/vendor/etc/init/adspstart.rc
rootdir/vendor/etc/init/cdspstart.rc
rootdir/vendor/etc/init/hw/init.common.rc

Not all platforms need {a,c}dspstart, and their initrc files with the
service declarations are only included on those that do. The start
commands however, to run these oneshot scripts after the necessary
partitions are mounted, are in a common initrc file, resulting in a
harmless yet misleading error:
init: Command 'start vendor.cdspstart_sh' action=fs (/vendor/etc/init/hw/init.pioneer.rc:96) took 0ms and failed: service vendor.cdspstart_sh not found
Note that a property is used to start the services right after
early-mounting, but before anything else (not guaranteed! This all runs
asynchronous). This may not be necessary, post-fs could be early enough
too.
---
@ix5 thoughts?
@chris42 This follows from our discussion last week :wink:

[COMMON] [DNM] init: Move {a,c}dspstart_sh start commands into optional service file

---

vintf/manifest.xml

This is already defined by interfaces.  [Google-git](https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-11.0.0_r3/wifi/1.4/default/android.hardware.wifi%401.0-service.xml)
Error:
`checkvintf E 09-15 21:15:46  1594  1594 VintfObject.cpp:66] getDeviceHalManifest: -2147483648 VINTF parse error: Cannot add manifest fragment /vendor/etc/vintf/manifest/android.hardware.wifi@1.0-service.xml:HAL "android.hardware.wifi" has a conflict.`

[R] vintf: Remove android.hardware.wifi

---

hardware/liblights/Android.mk
hardware/power/Android.mk

In Android Q libhidltransport was deprecated and all the symbols of this library were moved to libhidlbase.
Thus lets remove this library as it serves no purpose.
Commits that made those changes upstream:
https://android.googlesource.com/platform/system/libhidl/+/8f65ba713e73b40dc58dd7a8a702a96d6c1c2181
https://android.googlesource.com/platform/system/libhidl/+/a46371d5b3ffd08808ae93ec420721345738ec65
https://android.googlesource.com/platform/system/libhwbinder/+/09a8725d56b168668a11530537c9738f4bc58a90

liblights: Remove deprecated library from Android.mk

---

rootdir/vendor/etc/init/hw/init.common.rc

On R, verity state is better to be checked by bootloader instead of init in userspace.
`do_verity_load_state` is not be supported on R.
https://android-review.googlesource.com/c/platform/system/core/+/946923/3/init/builtins.cpp#b710
Error:
`host_init_verifier: device/sony/common/rootdir/vendor/etc/init/hw/init.common.rc: 69: Invalid keyword 'verity_load_state'`

[R]rootdir: init: Remove useless verity_load_state

---

common-treble.mk
vintf/manifest.xml

Android now includes vintf fragments for clearkey so the unnecessary and
wrongly versioned redeclaration is removed from our manifest.
Furthermore the service that is hosted with 1.2 or 1.3 is the same
except for vintf and the lazy interface version that is exposed.
Enforcing vintf expects us to declare exactly what is hosted, even if
1.2 should technically allow 1.3 to run:
I init    : starting service 'vendor.drm-clearkey-hal-1-2'...
I hwservicemanager: getTransport: Cannot find entry android.hardware.drm@1.3::IDrmFactory/clearkey in either framework or device manifest.
E HidlServiceManagement: Service android.hardware.drm@1.3::IDrmFactory/clearkey must be in VINTF manifest in order to register/get.
F android.hardware.drm@1.2-service.clearkey: Check failed: …

[COMMON] [R] Switch clearkey to version 1.3; all drm services to lazy

---

common-packages.mk

These libraries are deprecated, not referenced by any AOSP nor OSS HAL, but are still required by odm blobs (short term).  We don't add a dependency on the vndk variants as those end up in /system but require these in /vendor instead.
Submitting this to Q as well just in case, which received the same cleanups.

[Q/R] TEMPORARY: packages: Include deprecated hwbinder/hidltransport on vendor

---

vintf/vendor.hw.imsservices.xml

Vendor blobs for Android 11 host this new service:
E HidlServiceManagement: Service vendor.qti.ims.factory@1.0::IImsFactory/default must be in VINTF manifest in order to register/get.
F imsrcsd : ImsRcsBaseImpl.cpp:101] Check failed: ((ImsFactory*) m_pImsFactory)->registerAsService() == android::NO_ERROR (((ImsFactory*) m_pImsFactory)->registerAsService()=-2147483648, android::NO_ERROR=0) Failed to register ImsFactory HAL

[COMMON] [R/ODM] vintf: imsservices: Add IImsFactory and clean up fqname dupes

---

CommonConfig.mk
vintf/android.hardware.vibrator_v1.0.xml
vintf/android.hardware.vibrator_v1.2.xml
vintf/manifest.xml

Android R enforces strict matching of hosted service versions and the version declared in vintf; a mismatch, even if technically allowed by semver is denied and the service fails to register.
This is likely done in favour of strict consistency; declaring a lower version than what is hosted previously (Android Q) allowed interface consumers to use that higher version without being limited by vintf, making it partly useless to reflect exactly what it hosted unless mandated by a targeted FCM.

[COMMON] [R] Update vintf versions for strict matching

---

overlay/frameworks/base/core/res/res/values/config.xml

Supersedes #740
This new config contains updated paths for framework files which moved into apex, deduplicates some entries and adds more files to be pinned.
No errors are observed on Griffin running Android 11, all files are present.

[COMMON] [R] Import AOSP pinner configuration

---

common.mk
overlay/packages/apps/Bluetooth/res/values/config.xml
rootdir/vendor/etc/sysconfig/component-overrides.xml

Runtime Resource Overlays (RROs) can no longer change the value of
resources in manifest when read during PackagerParser.
This change uses component-override to enable the service by default
on all devices.
Remove usages of profile_supported_sap from overlays as they no
longer configure the enable state of .sap.SapService.
Bug: 135048762
Test: adb shell pm query-services \
com.android.bluetooth/.sap.SapService
Change-Id: If41df9fdefbcd952f8387451dc137565343e3d75
---
@sjllls thanks for bringing this one to my attention! After looking closer at the logs it's pretty obvious why this happens:
```log
W ActivityManager: Unable to start service Intent { cmp=com.android.bluetooth/.sap.SapService (has extras) } U=0: not found
```
Fine, Sim Access Profile should be optional... Then later in the …

[COMMON] [R] Re-enable "required" Bluetooth SapService

---

common-packages.mk

`libavservices_minijail` is `vendor_available`, meaning that a `PRODUCT_PACKAGES` dependency on it includes its system variant. This is _not_ part of the vndk and hence unavailable to odm blobs, leaving:
F linker  : CANNOT LINK EXECUTABLE "/odm/bin/ims_rtp_daemon": library "libavservices_minijail.so" not found: needed by main executable
in place. Neither would that approach suffice for GSIs. Use a vendor
dependency to ensure the library is included in /vendor and available to
blobs.
(sidenote: Another 32-bit transitive dependency already includes this
library, this merely adds the 64-bit library for `ims_rtp_daemon`)
Fixes: 820955e5f6df3554ced911c17fbaebd2502c1ab1

[COMMON] [R] Include vendor variant of libavservices_minijail

---

common-prop.mk
common-treble.mk
vintf/manifest.xml

Depends on https://github.com/sonyxperiadev/vendor-qcom-opensource-audio-hal-primary-hal/pull/8
The new API interface contains, among which, a new audio patch updating function to support more quickly and efficiently rerouting an audio stream without disruption. Despite the new (NICOBAR 9.11) CAF audio HAL supporting this function, no improvement is noticed when switching between speakers and BT headphones (assuming A2DP offloading - a feature that has not yet made it to sonyxperiadev repos but is in testing locally - which routes audio through the HAL and DSP for BT instead of Androids software bluetooth playback "device").
See the above PR for more details about testing progress!

[COMMON] [R] [2/3] TESTME: Update to audio@6.0 (HAL 3.0)

---

CommonConfig.mk
vintf/android.hardware.secure_element_ds.xml
vintf/android.hardware.secure_element_ss.xml
vintf/vendor.nxp.nxpnfc.xml

Continuation of #720 and #792 
Qcrild provides access to the UICC through a Secure Element interface. Add a SS and DS vintf manifest to allow this interface to be hosted and retrieved.
Also clean up the vintf for NXP NFC, which was part of the original PR that covered SE for NFC (eSE1) as well.
@jerpelea Can you rebase master as soon as this lands on Q?

[COMMON] [Q/R] vintf: Add Secure Element interface for SIM cards (UICC)

---

common-perm.mk

See also: https://github.com/sonyxperiadev/device-sony-kumano/pull/50
All devices on Stock (Ganges, Tama, Kumano, Seine) Android 10 (where this permission was first introduced) have UICC-based host card emulation. Enable it globally and sort the list of files for easy updating in the future.

[COMMON] [Q/R] [2/2] perm: Add android.hardware.nfc.uicc

---

CommonConfig.mk
common.mk

See https://r.android.com/1457443
The variable also needs to be set earlier now since it's read-only by the time `CommonConfig.mk` is read.
Groundhog day, yada yada. The CADT is strong with El Goog.

[master] common: Update vendor boot variable

---

CommonConfig.mk

There is no need nowadays to rely on `AUTO` platform features.
Depends on https://github.com/sonyxperiadev/local_manifests/pull/115 to build successfully on `yoshino`.

[master] Disable TARGET_BOARD_AUTO

---

common.mk

This is defaulted to yes so regular SODP builds won't be affected, but ROMs like PE enforce the use of their own APNs and that causes a double definition.

[Master] common : Add a guard to allow use of other APNs config

---

common-odm.mk
hardware/odm/Android.mk

Certain props need to be filtered out from the proprietary `odm` image ("Software Binaries") because they are device-specific, while the `odm` image is released per platform.

[q-mr1] odm: Add build.prop cleaner

---

hardware/odm/Android.mk

We need to be a bit more thorough since `ro.odm.product.*` etc. can also be generated.
Explanation:
`sed -i '/ro.product.odm/d` only cleans every line containing `ro.product.odm`.
`sed -i '/^ro.odm.version/!d` removes every line _not_ starting with `ro.odm.version`.

[q-mr1] odm: Only leave ro.odm.expect in build.prop

---

hardware/qcom/Android.mk

Without this we would fallback to sdm660-libion media HAL which is wrong.
Add sm8250 to the lists so that the correct HALs are used.

hardware/qcom/Android.mk: Add sm8250 (KONA) to media platform lists.

---

common-odm.mk

If we want camera working on Edo devices we need to include the
camera.sm8250 blob.

common-odm.mk: Add edo to filter and add camera.sm8250

---

rootdir/Android.bp
rootdir/Android.mk

All boards listed here and new (unlisted!) SM8250 are the only ones supported by SODP R. Remove the guard entirely.

[COMMON] [MASTER] rootdir: Unconditionally provide pd_mapper and tftp_server rcs

---

rootdir/vendor/etc/init/netmgrd.rc

External modem network is managed by netmgrd.
This is the case with SDX55 on SM8250/SDA865.

[COMMON] init: netmgrd: Start netmgr daemon for external modem

---

common-init.mk
rootdir/Android.bp
rootdir/vendor/etc/init/atfwd.rc
rootdir/vendor/etc/init/hw/init.common.rc
rootdir/vendor/etc/init/mdm_helper.rc

The Edo platform has an external SDX55 PCIe modem: add the
mdm helper to initialize it.

[COMMON] common: MDM helper and new directory

---

common-treble.mk

The new sensor module on Edo needs/takes advantage of the extended API in sensors v2.
As far as I'm aware the libhardware interface hasn't changed, or at least not in such a way that we couldn't use 2.X on other platforms.  This change should be safe to merge if that works as normal, and otherwise all supported devices are expected to get recompiled with newer code that should support all this so that we can stick with one consistent, shared software stack (ie. no hacks to keep Edo at 9.x branches while the rest lives on at 7.x or 8.x).
Notes:
- This requires sensors.ssc.so (the libhw module) to reside under hw/ again, finally;
- Remove android.hardware.sensors@1.0 from vintf (2.X includes its own vintf fragment);
- One of the libs tries to open display mapper 1.1... Otherwise …

[DONOTMERGE] [COMMON] [master] common-treble: Migrate to sensors@2.1 multihal

---

common-treble.mk
vintf/manifest.xml

Cleaned up resubmission from #/820, this time iwithout donotmerge, notes and old commented-out bits :)
---
The new sensor module on edo needs/takes advantage of the extended API
in sensors v2. In due time all other platforms will receive the same
upgraded libhardware module and friends.
Notable changes:
- `sensors.ssc.so` (which is a libhardware module) finally resides under
`hw/` again;
- The multihal includes its own vintf fragment, no need to declare this
in our own file anymore;
- The new module strangely depends on diplay mapper 1.1 and 3.0, which
have been explicitly included on the vendor partition (`.vendor`
postfix):
Type                 Name/Value
...
(NEEDED)             Shared library: [android.hardware.graphics.mapper@3.0.so]
(NEEDED)             Shared library: …

[COMMON] [MASTER] [RESUBMIT] common-treble,vintf: Migrate to sensors@2.1 multihal

---

common-odm.mk
rootdir/vendor/etc/init/sscrpcd.rc

This daemon can set a wakelock and will fail to initialize if it
has no permission to.

[COMMON] vendor: init: sscrpcd: Add wakelock group to sensor dsp daemon

---

rootdir/vendor/etc/init/rmt_storage.rc

Fixes confusing logspam for `mdm` targets:
```
E vendor.rmt_storage: Remote storage service is not supported on mdm target
```

[r-mr1] rootdir: rmt_storage: Enabled based on baseband

---

hardware/camera/Android.mk

Sorry, forgot to submit this yesterday!
---
CamX on Edo needs these symlinks. We should probably come up with a better method of representing this instead of hardcoding SoC names in common.

[common] [R] hardware/camera: Emit symlinks for sm8250

---

common.mk

Makes testing things possible with enforcing AVB and verity.
Also clean up rdclean.sh guards, we can use PRODUCT_PACKAGES_DEBUG for userdebug+eng builds in Q.

common: Inherit GSI AVB pubkeys for Google GSIs

---

common-packages.mk
common-treble.mk
vintf/manifest.xml

Depends on https://github.com/sonyxperiadev/hardware-qcom-gps/pull/6 and https://github.com/sonyxperiadev/device-sony-sepolicy/pull/595
9.12 branches support the new functionality introduced with the .1 minor interface release; use it. It is unclear why the `gps` repository still maintains a copy of the 2.0 version of the binary, that interface is still provided by the 2.1 HAL by definition (in fact the HAL also registers interfaces for 1.0 and 1.1).

[common] [R/master] Upgrade to gnss 2.1

---

vintf/manifest.xml

Both 8.1 and 9.12 branches of the `gps` repository already provide declarations for the `IGnss` interface by a vintf fragment that's included with `android.hardware.gnss@2.0-service-qti`.
---
@jerpelea Are there still plans to rebase R on Q or are we just shelving that for `common`? Seems the last time was at least 3 months ago.

[common] [Q/R/master] vintf: Drop gnss interface; already provided by vintf fragment

---

common-treble.mk
hardware/health/Android.bp
vintf/manifest.xml

DNM: Hold off until R when `libhealthservice` is available to recovery.
For more info: https://android.googlesource.com/platform/hardware/interfaces/+/refs/tags/android-r-preview-4/health/2.1/
Also don't forget to assign an sepolicy label for the recovery exec.

[r-mr1] health: Add to recovery, use vintf_fragments

---

Android.bp
common.mk

Place all blueprint-defined packages in `common` (mostly `prebuilt_etc`) under a namespace so that external devices cannot see nor are affected by these targets being defined. For example a device defined outside of Sony cannot redefine a target or copy rule that provides the same file
as our prebuilt packages.
This is pretty much analogous to the build-guard in the top-level Android.mk in this repository.
Build-tested on PDX206.

[common] [R] Add blueprint guard (soong_namespace) around all packages

---

rootdir/vendor/etc/init/rmt_storage.rc

Closes https://github.com/sonyxperiadev/bug_tracker/issues/679.
https://github.com/sonyxperiadev/bug_tracker/issues/679 reports issues with the modem failing to start. The log is pretty clear on why rmt_storage is not coming up:
I init    : Parsing file /vendor/etc/init/rmt_storage.rc...
E init    : /vendor/etc/init/rmt_storage.rc: 10: ParseTriggers() failed: && is the only symbol allowed to concatenate actions
E init    : /vendor/etc/init/rmt_storage.rc: 14: ParseTriggers() failed: && is the only symbol allowed to concatenate actions
A recent commit disabled rmt_storage for `mdm` basebands by only starting on `sdm` and `msm` basebands, but a colon got lost along the way.
Fixes: 28921cff ("rootdir: rmt_storage: Enabled based on baseband")

[URGENT] [COMMON] [R] rmt_storage: Add missing colon in property triggers to enable service

---

CommonConfig.mk
vintf/android.hw.qcradio_ds.xml
vintf/android.hw.qcradio_ss.xml
vintf/vendor.hw.qcradio_ds.xml
vintf/vendor.hw.qcradio_ss.xml
vintf/vendor.hw.radio_ds.xml
vintf/vendor.hw.radio_ss.xml

In the new ODM V4 blobs services host higher version then we specify.
Bump the version of the services (Check commits for logs)
While at it remove unwanted duplication.

[R] VINTF: Remove duplicates, Bump versions

---

vintf/android.hardware.secure_element_ds.xml
vintf/android.hardware.secure_element_ss.xml

New ODM v4 blobs host the ISecureElement interface at 1.2 now, not 1.0:
I hwservicemanager: getTransport: Cannot find entry android.hardware.secure_element@1.2::ISecureElement/SIM1 in either framework or device manifest.
E HidlServiceManagement: Service android.hardware.secure_element@1.2::ISecureElement/SIM1 must be in VINTF manifest in order to register/get.
I hwservicemanager: getTransport: Cannot find entry android.hardware.secure_element@1.2::ISecureElement/SIM2 in either framework or device manifest.
E HidlServiceManagement: Service android.hardware.secure_element@1.2::ISecureElement/SIM2 must be in VINTF manifest in order to register/get.
Signed-off-by: Marijn Suijten <marijns95@gmail.com>

[common] [R] vintf/secure_element: Bump ISecureElement interface to 1.2 

---

rootdir/system/system_ext/etc/permissions/privapp-permissions-ims.xml

After this [commit](https://github.com/PixelExperience-Devices/device_sony_customization/commit/257a449540b616d2cf32af9b6624fb1b8f1b4bb9#diff-c2912b8c99febfbc46b6fef0d31cac8d3d131ee8e3b63617221d4f154a614f3f) we need these 3 new permissions for Pixel Experience to boot again.
Error:
```
Signature|privileged permissions not in privapp-permissions whitelist:
org.codeaurora.ims (/system/system_ext/priv-app/ims): android.permission.WRITE_SECURE_SETTINGS,
org.codeaurora.ims (/system/system_ext/priv-app/ims): android.permission.READ_PRIVILEGED_PHONE_STATE,
org.codeaurora.ims (/system/system_ext/priv-app/ims): android.permission.MODIFY_PHONE_STATE,
```
Tested-by: Paulbouchara

[r-mr1] priv-permissions-ims.xml: Add newly required permissions

---

common.mk

This change will allow multiple kernel versions to live side-by-side in one AOSP tree.
Needs to be accompanied by changes to kernel-headers repos to change module name to `qti_kernel_headers_X.Y` and an
auxiliary module to resolve `qti_kernel_headers` to the correct module.
Overview:
- https://github.com/sonyxperiadev/device-sony-common/pull/839
- https://github.com/sonyxperiadev/device-sony-common-headers/pull/16
- https://github.com/sonyxperiadev/device-sony-common-headers/pull/15
- https://github.com/ix5/qti-headers (to be forked and then placed into `kernel/sony/qti-headers`)

[r-mr1] common: Set qti-headers kernel version via soong

---

common.mk

This change will allow multiple kernel versions to live side-by-side in one AOSP tree.
Needs to be accompanied by changes to kernel-headers repos to change module name to `qti_kernel_headers_X.Y` and an auxiliary module to resolve `qti_kernel_headers` to the correct module.

[q-mr1] common: Set qti-headers kernel version via soong

---

common-treble.mk

As mentioned in 28d88a2a ("common-treble: SM8250+ Composer is a binary instead of passthrough HAL") the `-service` is responsible for loading the libhardware module on our SM8150 HAL as well without an SP-HAL `-impl` library available.  Drop this inexistant dependency.

[R] common-treble: Drop inexistant composer -impl library dependency

---

rootdir/vendor/etc/init/hw/init.common.rc

And drop legacy composer and allocator starts, all supported devices on R are "GRAPHICS_V3".  See also 983fedae ("common-treble: remove deprecated display packages").

[R] init.common: Add early-start for new (SM8250) composer service name

---

common-binds.mk

These jars are missing.
In device system_ext:
```
pdx201:/system_ext/framework # ls
QtiTelephonyServicelibrary.jar
com.qti.dpmframework.jar
com.qualcomm.qti.imscmservice-V2.0-java.jar
com.qualcomm.qti.imscmservice-V2.1-java.jar
com.qualcomm.qti.imscmservice-V2.2-java.jar
dpmapi.jar
embmslibrary.jar
qcrilhook.jar
qti-telephony-hidl-wrapper.jar
qti-telephony-utils.jar
uimgbalibrary.jar
uimgbamanagerlibrary.jar
uimlpalibrary.jar
uimremoteclientlibrary.jar
uimremoteserverlibrary.jar
uimservicelibrary.jar
vendor.qti.data.factory-V1.0-java.jar
vendor.qti.data.factory-V2.0-java.jar
vendor.qti.hardware.data.connection-V1.0-java.jar
vendor.qti.hardware.data.connection-V1.1-java.jar
vendor.qti.hardware.data.dynamicdds-V1.0-java.jar
vendor.qti.ims.rcsconfig-V1.0-java.jar
```
In odm:
``` …
```

[r-mr1] common-binds.mk: Add missing bindmount for ims-ext-common.jar

---

rootdir/vendor/etc/init/bindmount-apps.rc

They moved to /odm/system_ext/lib64, thanks @MarijnS95 .

[r-mr1] common: init: Fix ims ViLTE blobs path

---

vintf/vendor.hw.imsservices.xml

Some of these duplicates were missed in the previous commit, most likely due to a later rebase where new hals were added.

[R] vinf/imsservices: Remove version/interface dupes in favour of fqname

---

rootdir/vendor/etc/init/hw/init.common.rc

See https://github.com/sonyxperiadev/bug_tracker/issues/699#issuecomment-881286551;
none of the devices supported on R and beyond use the fbdev driver
anymore, hence none of these `/sys` files exist.  Remove the operations
to free some space and get rid of irrelevant errors in dmesg/logcat.

[R] init.common: Remove legacy ownership changes on fbdev files

---

vintf/vendor.hw.imsservices.xml

The new ODM V5b host the interface at 3.0
07-15 01:26:44.528   504   504 I hwservicemanager: getTransport: Cannot find entry vendor.qti.imsrtpservice@3.0::IRTPService/imsrtpservice in either framework or device manifest.
07-15 01:26:44.529  1428  1428 E HidlServiceManagement: Service vendor.qti.imsrtpservice@3.0::IRTPService/imsrtpservice must be in VINTF manifest in order to register/get.

imsrtpservice : Bump to 3.0

---

rootdir/vendor/etc/init/init.usb.rc

sys.usb.configfs from init.usb.rc is triggering generic rules found in
/system/etc/init/hw/init.usb.configfs.rc which leads to the fact that
the values that correspond to the real configuration of the device are
overwritten by the generic (dummy) ones. Because of this, some USB modes
such as USB tethering, cannot be enabled in the USB Preferences menu.
Hence, change the prefix of sys.usb.configfs setting from "sys." to
"vendor." in order to avoid triggering the behavior described above.
The change was successfully tested on Xperia 10+ (Mermaid) device,
MTP, PTP, MIDI and USB tethering modes are enabled successfully and each
of them was recognized by the PC.

[q-mr1] Fix USB composition selector

---

common-treble.mk

Add android.hardware.usb@1.2-service-qti HAL for devices
running on 4.19 kernel.
This version of the USB HAL is not intended to be used
on targets with kernels older than 4.19 (since it relies on
Type-C Class to be enabled).

[master] Add support for QTI USB HAL

---

common-prop.mk
hardware/adreno/Android.mk

Fixes https://github.com/sonyxperiadev/bug_tracker/issues/718
Android is continuously clamping down on symlink hacks (see the report in [1]) and for a good reason: they provide a perfectly valid alternative using `ro.hardware.<module name>` to change the platform name of a module that needs to be searched for.  On all our platforms the Vulkan library is called `vulkan.qcom.so` instead of `vulkan.$(TARGET_BOARD_PLATFORM).so` and Android can simply be taught to search for the former instead of the latter by setting `ro.hardware.vulkan=qcom`.
[1]: https://github.com/sonyxperiadev/bug_tracker/issues/718
Signed-off-by: Marijn Suijten <marijn.suijten@somainline.org>

[Q] hardware/adreno: Convert vendor->odm symlink to ro.hardware property

---

vintf/vendor.hw.dataservices.xml

* It is required
* E HidlServiceManagement: Service vendor.qti.data.factory@2.2::IFactory/default must be in VINTF manifest in order to register/get.
Signed-off-by: electimon <electimon@gmail.com>

vintf: Bump vendor.qti.data.factory::IFactory version to 2.2

---

hardware/adreno/Android.mk

Commit 0aecc439 ("hardware/adreno: Convert vendor->odm symlink to ro.hardware property") cleaned up the Vulkan Adreno blob links by using `ro.hardware.vulkan=qcom` to search for a qcom-vendored blob instead of one specifically named after the current board.  However, this also dropped the symlink from vendor to odm which is necessary for Android to find the module.  Android loads this hardware module from the sphal namespace [1] which is allowed to load from both /odm/${LIB} and /vendor/${LIB}, but is only searching in the hw/ subdirectory of /vendor/${LIB} [2].
Directly symlinking from /odm/${LIB} into /odm/${LIB}/hw is possible however since sphal _is_ instructed to _search_ there, but this requires and odm change and a new release; instead restore the previous symlink from /vendor's …

hardware/adreno: Add back vendor->odm symlink for `vulkan.qcom.so`

---

common-treble.mk

Following the commit f19703e ("common-treble: Provide radio, keymaster
and secure_element HAL on vendor"), starting with Android 12 most HAL
libraries are not included in VNDK anymore - they need to be explicitly
pulled in to `/vendor` for odm blobs to be allowed to access them:
QCamera : <MCI><ERROR> mm_camera_load_shim_lib: 3306: dlopen failed
with error dlopen failed: library
"android.frameworks.sensorservice@1.0.so" not found: needed by
/odm/lib/libmmcamera2_stats_modules.so in namespace (default)
android.frameworks.sensorservice@1.0 is used by at least mm-camera
framework.

[s-mr1] common-treble: Provide android.frameworks.sensorservice@1.0 on vendor

---

common.mk

None of our devices set BOARD_BOOT_HEADER_VERSION, which must be at least version 3 for vendor_boot to be enabled by default, as per the AOSP change that this was originally explicitly disabled for: https://r.android.com/1457443 - it'll stay disabled for all our platforms without explicitly setting this to `false`.
Removing this explicit disablement will allow us to enable the feature on newer platforms like Sagami where vendor_boot is required.
Build- and boot-tested on XQ-AU52 (PDX201 DSDS, Seine, Xperia 10 II) running Android 12, and J9110 (Griffin DSDS, Kumano, Xperia 1) running Android 11, no vendor_boot.img is generated and the device functions as normal.
Fixes: f570b264 ("common: Update vendor boot variable")
CC @ix5

[R/S] common: Don't explicitly disable vendor boot

---

overlay/frameworks/base/core/res/res/values/config.xml

Set default behavior when the user long presses the power button.
This allows to call the power menu with a long press of the power
button. If the default value is set to 5 (Go to assistant), the fallback
to the old behavior will not work when "Hold for Assistant" is disabled.
Reference:
https://android.googlesource.com/platform/packages/apps/Settings/+/34cbca502bdfd6e0e5fff836bb9b0a3abf6811ea

[s-mr1] overlay: base: Set default value of config_longPressOnPowerBehavior

---

common-prop.mk

This patch is aimed to disable APEX compression on 4.14 SODP devices rendering them unable to boot with compressed APEX.

common-prop : Disable compressed APEX for 4.14 kernel

---

common-treble.mk

Fixes https://github.com/sonyxperiadev/bug_tracker/issues/740
AOSP switched up the default implementation from GPT flags to the `/misc` partition in the default implementation (`-impl` lib and `libboot_control.so`) for 1.1 [1], which is incorrect on our Qualcomm boards.  As we'd still like to switch to the 1.1 interface for FCM5 compatibility, and would like to drop the legacy libhardware module (see `bootctl.<platform>` in the respective platform directories, and its implementation in `hardware/qcom/bootctrl`) we'll use the updated CAF repository directly.
Note that we still include AOSP's 1.1 passthrough library loader.  As usual, this provides us with the right init .rc and vintf fragment, and allows starting both a 1.0 and 1.1 passthrough (`-impl`) library.  It is this `-impl` library …

[R/S] common-treble: Switch to CAF bootctrl 1.1 HAL

---

rootdir/vendor/etc/seccomp_policy/mediacodec.policy

Updated from vendor-qcom-opensource-media as of 182649923d3813e2e539a0e36d83b3e70dcfcc4a:
https://github.com/sonyxperiadev/vendor-qcom-opensource-media/tree/182649923d3813e2e539a0e36d83b3e70dcfcc4a

[R/S] mediacodec: Update seccomp polic from CAF.

---

rootdir/init.recovery.common.rc
rootdir/vendor/etc/init/init.usb.rc

- init.recovery: Only perform USB setup once, and set mode to peripheral
- init.recovery,init.usb: Set UDC mode to peripheral

[S] clean up USB and set peripheral mode for Sagami

---

rootdir/vendor/etc/init/qcrild.rc

On R the service is still called "ril-daemon".
This fixes random SIM detection https://github.com/sonyxperiadev/bug_tracker/issues/736.
This reverts commit 30b54ba54619cc17bfc8bfd7a56d8e235579431a.

Revert "init: qcrild.rc : Add vendor prefix to ril-daemon"

---

rootdir/vendor/oem/modem-config/S236.1/modem.conf
rootdir/vendor/oem/modem-config/S236.2/modem.conf
rootdir/vendor/oem/modem-config/S237.3/modem.conf
rootdir/vendor/oem/modem-config/S238.1/modem.conf
rootdir/vendor/oem/modem-config/S238.2/modem.conf

This adds modem config files for the following providers,
- Turkcell
- Turk Telekom
- Vodafone
Firmware files are extracted from latest stock ROM (52.1.A.3.49) at /vendor/firmware_mnt/image/modem_pr/mcfg/configs

Add modem config files for Turkish providers

---

hardware/camera/Android.mk
hardware/qcom/Android.mk
hardware/tftp/Android.mk

Not all custom ROMs use `KONA = sm8250`. For example, the lineage uses `KONA = kona`. It'll cause problems to hard-code `sm8250` everywhere.
This PR replaces all hard-coded sm8250 that is used for detecting `TARGET_BOARD_PLATFORM` to `$(KONA)`.

Replace sm8250 with $(KONA)

---

hardware/camera/Android.mk
hardware/qcom/Android.mk
hardware/tftp/Android.mk

These variables are in place to have a custom SoC name for a given SoC project (SODP uses the former "part number", whereas other SODP-based ROMs may opt for the SoC project name), but were only recently adjusted to use the variable name for KONA/sm8250 in a very nondescriptive patch.  Address this for the remaining SoCs with such a variable name.

hardware: Replace hardcoded `sm6125 sm6350 sm8150` with `$(TRINKET) $(LITO) $(MSMNILE)`

---

rootdir/vendor/oem/modem-config/S256.1/modem.conf
rootdir/vendor/oem/modem-config/S256.2/modem.conf
rootdir/vendor/oem/modem-config/S257.1/modem.conf
rootdir/vendor/oem/modem-config/S257.2/modem.conf

This adds modem configs for the Finnish Elisa and DNA providers.
The firmware files reside at
/vendor/firmware_mnt/image/modem_pr/mcfg/configs
The IDs are listed at [service_provider_sim_configs.xml](https://github.com/sonyxperiadev/SonyOpenTelephony/blob/master/ModemConfig/res/xml/service_provider_sim_configs.xml#L708) but were missing a modem.conf.

Add modem configs for Finnish providers Elisa and DNA

---

hardware/health/android.hardware.health@2.0-service.sony.rc

On at least our Sagami class of devices the kernel battery driver (including SoMC charger extensions) probes/registers later than the start of our `health` HAL, resulting in it not seeing the battery until a restart.  The power supply arrives as soon as adsp is booted, which is our signal to kick-start the HAL.
Note that we could also have a `wait /sys/class/power_supply/battery` on another `on <xxx>` trigger that starts _later_ than adspstart, but this'll block the entire trigger until a power supply arrives.

[S] hardware/health: Wait for adsp and `power_supply/battery` before starting health HAL

---

common-treble.mk

Since wpa-suppliant is now switched to AIDL, it no longer
builds the HIDL interfaces that the prebuilt software binaries
need.
Build the HIDL interface to make the prebuilt executable happy.

common-treble.mk: Build hostapd libraries

---

common-treble.mk
vintf/manifest.xml

Tested on lena (pdx213) and sagami (pdx215).

enable external camera support on Android 13

---

common-packages.mk
common.mk

Android [finally cut down on vendor access] to the system-only `audio.a2dp.default` and `audio.hearing_aid.default` libhardware modules, which have already been deprecated and replaced with the much more modern HIDL+fqm `audio.bluetooth.default` _vendor_ libhardware module. The modules reside on `/system` where they [can't be loaded anyway when VNDK is enabled]:
E DevicesFactoryHAL: loadAudioInterface couldn't load audio hw module audio.a2dp (No such file or directory)
W DevicesFactoryHalHidl: The specified device name is not recognized: "a2dp"
E AudioFlinger: loadHwModule() error -22 loading module a2dp
W APM_AudioPolicyManager: could not open HW module a2dp
This policy isn't reachable anyway unless the new Bluetooth Audio HAL is explicitly disabled by setting …

[T] Remove reliance on deprecated a2dp/hearing_aid system audio modules

---

CommonConfig.mk
vintf/vendor.qualcomm.qti.dpm.xml

This service was originally added in a5f7f38c ("vintf: Add com.qualcomm.qti.dpm.api::IdpmQmi@1.0") and later had a deprecated `vendor.qti.dpm.api` entry (hosting the same interface) renamed to it in 81835713 ("qcrild.rc: add new ril services") via the `vendor.hw.dataservices.xml` file.  The former commit should have likely renamed it outright, instead of adding a new definition, and Android 14 now rightfully complains that it found a duplicate:
getDeviceHalManifest: -22 VINTF parse error: Illformed file: /vendor/etc/vintf/manifest.xml: Duplicated manifest.hal entry com.qualcomm.qti.dpm.api: Conflicting FqInstance: @1.0::IdpmQmi/dpmQmiService (from /vendor/etc/vintf/manifest.xml) vs. @1.0::IdpmQmi/dpmQmiService (from /vendor/etc/vintf/manifest.xml). Check whether or not multiple modules …

[T/U] vintf: Drop duplicate `com.qualcomm.qti.dpm.api` definition

---

rootdir/vendor/etc/data/dsi_config.xml
rootdir/vendor/etc/data/netmgr_config.xml

SoC Lahaina with SOC_IDs 415 and 439 use the 'lahaina_pt' configuration.
E QC-NETMGR-LIB: netmgr_main_process_target: unable to load config for target:lahaina_pt

[t-mr1] vendor: data: Add configuration for SoC Lahaina

---

common-prop.mk

A recent AOSP change[1] has put a hard dependency on ro.hardware.egl or equivalent property being set, otherwise it fails to load EGL libraries successfully:
D libEGL  : Failed to load drivers from property ro.board.platform
with value sm8450
F libEGL  : couldn't find an OpenGL ES implementation, make sure
one of persist.graphics.egl, ro.hardware.egl and
ro.board.platform is set
--------- beginning of crash
F DEBUG   : Cmdline: /system/bin/surfaceflinger
F DEBUG   : pid: 573, tid: 600, name: surfaceflinger  >>> /system/bin/surfaceflinger <<<
F DEBUG   : uid: 1000
F DEBUG   : tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
F DEBUG   : Abort message: 'couldn't find an OpenGL ES implementation,
make sure one …

[u-mr1] common-prop: Set ro.hardware.egl property

---

common-prop.mk
common-treble.mk
common.mk

1. Remove leftover kernel 4.14 barriers. The current minimum supported kernel version is 4.19.
2. Add support for SM8550 display HAL, which will be used for devices running on kernel 5.15.
3. Remove display properties from common, because they are specific for each platform and set of blobs, moreover, some are completely outdated.

[t-mr1] Add support for SM8550 (k5.15) display HAL

---

CommonConfig.mk
common-treble.mk
common.mk
hardware/qcom/Android.mk
rootdir/vendor/etc/init/hw/init.common.rc
vintf/manifest.xml
vintf/vendor.qti.hardware.audio.xml

Implement changes required for Audioreach audio subsystem.
1. Bump audio implementation to 7.1 (All current supported platforms should receive audio
policy updates in accordance with[1])
2. Bump audio effect implementation to 7.0.
3. Bump soundtrigger implementation to 2.3.
4. Switch to 64bit audio service.
Changes tested on at least one device from each supported platform except Lena.
[1] https://source.android.com/docs/core/audio/hidl-implement#xml-schema-hal7

[t-mr1] Inital Audioreach customization

---

hardware/health/CycleCountBackupRestore.cpp
hardware/health/CycleCountBackupRestore.h
hardware/health/LearnedCapacityBackupRestore.cpp
hardware/health/LearnedCapacityBackupRestore.h
rootdir/vendor/etc/init/hw/init.common.rc

Restart Health HAL when ADSP is out of reset.
On devices where communication with the battery occurs over GLINK,
it is important that Health HAL is (re)launched after ADSP ready.
This is reimplementation of https://github.com/sonyxperiadev/device-sony-common/commit/7814953e62a8b4f48e51fe8f3ddebbbca51aebd5 ("hardware/health: Wait for
adsp and power_supply/battery before starting health HAL") which
was removed in https://github.com/sonyxperiadev/device-sony-common/commit/57da52d8d8bfdf02a8506edcb276fe2fe0657172 ("hardware/health: Upgrade to 2.1 via
libhealth2impl").
This brings back the working battery status on platforms such as Sagami, Nagara and Yodo.

[t-mr1] etc: init.common.rc: Restart Health HAL when ADSP ready

---

CommonConfig.mk
common-init.mk
common-odm-camx.mk
common-treble.mk
rootdir/Android.bp
rootdir/vendor/etc/init/vendor.qti.camera.provider.rc
vintf/android.hardware.camera.provider.xml
vintf/manifest.xml
vintf/vendor.qti.camera.provider.xml

Add vendor.qti.camera.provider.rc + vintf.
vendor.qti.hardware.camera.aon typo fix.
Wrap legacy camera provider packages with TARGET_USES_QTI_CAMERA.

[t-mr1] Add QTI camera service

---

vintf/android.hardware.camera.provider.xml
vintf/manifest.xml
vintf/vendor.qti.camera.provider.xml

For devices without TARGET_USES_QTI_CAMERA, we have generated manifest that defines 
```xml
<hal format="hidl">
<name>android.hardware.camera.provider</name>
<transport>hwbinder</transport>
<version>2.5</version>
```
twice. Once in vintf/manifest.xml and once in vintf/android.hardware.camera.provider.xml.
This PR keeps the same functionality as before by merging the both definitions in android.hardware.camera.provider.xml and adding a definition in vintf/vendor.qti.camera.provider.xml.
Limited testing so far, fixes compilation issue on nagara.
Fixes: https://github.com/sonyxperiadev/bug_tracker/issues/846

[t-mr1] Avoid duplicate definition of camera provider

---

CommonConfig.mk
common-packages.mk
common-treble.mk
common.mk
rootdir/vendor/etc/public.libraries.txt
vintf/framework_compatibility_matrix.xml
vintf/manifest.xml
vintf/vendor.hw.qtiradio_ss.xml

1. FCM bump to version 5.
2. Add prebuilt versioned protobuf.
3. Add framework compatibility matrix.
4. Add RIL dependencies which are no longer supplied by default.
Tested on:
**Edo.** Built and boots[1].
**Seine.** Built and boots[1].
**Lena.** Built only test[1].
**Murray.** Built and boots.
**Sagami.** Built and boots.
**Nagara.** Built and boots[2].
**Yodo.** Built and boots[2].
[1] The device stuck on bootanimation for about a few minutes, and then it successfully boots. The regression is common for all devices running on 4.19 kernel. Fix will be sent in the following patches as soon as the cause is localized.
[2] Fresh android.hardware.security.keymint-service-qti ODM binary is required. With it device smoothly boots.
Fixes: https://github.com/sonyxperiadev/bug_tracker/issues/848

[u-mr1] Android AP2A changes

---

vintf/framework_compatibility_matrix.xml

ERROR: files are incompatible: The following instances are in the
device manifest but not specified in framework compatibility matrix:
vendor.qti.hardware.camera.aon@1.3::IAONService/aoncameraservice

[u-mr1] vintf: Add vendor.qti.hardware.camera.aon to FCM

---

rootdir/vendor/etc/data/dsi_config.xml
rootdir/vendor/etc/data/netmgr_config.xml

Add data configuration for SoC Parrot.
Placed before Kailua instead of at the end of the list
to maintain the chronological order of the SoC release.

[u-mr1] vendor: data: Add configuration for SoC Parrot

---

vintf/framework_compatibility_matrix.xml

ERROR: files are incompatible: The following instances are in the
device manifest but not specified in framework compatibility matrix:
vendor.qti.hardware.display.config.IDisplayConfig/default (@5)
Fixes: https://github.com/sonyxperiadev/device-sony-common/issues/931

[u-mr1] vintf: Add vendor.qti.hardware.display.config v5 to FCM

---

common.mk

- common: Switch 5.10 kernel targets to AudioReach
All targets released with 5.10 kernel use AudioReach
framework by default.
- common: Protect audio HAL selection with TARGET_USES_AUDIOREACH
Some platforms (Murray and Zambezi in our case) that are
ported from older kernel version are forced to use legacy
audio HAL due to the incompatibility of the ADSP firmware
with AudioReach. Because of this reason, the audio HAL must
be detected regardless of the kernel version.

[u-mr1] AudioReach on 5.10 targets

---

common-init.mk
common-treble.mk
common.mk
rootdir/vendor/bin/init.qcom.adspstart.sh
rootdir/vendor/bin/init.qcom.cdspstart.sh
rootdir/vendor/bin/init.qcom.slpistart.sh
rootdir/vendor/etc/init/sdsp-sensorspdr.rc
rootdir/vendor/etc/init/sensors.rc
rootdir/vendor/etc/init/slpistart.rc
rootdir/vendor/etc/sensors/hals.conf
rootdir/vendor/etc/sensors/sns_reg_config

This patch is an addition to the previous PR https://github.com/sonyxperiadev/device-sony-common/pull/938 and completed the migration to AIDL Sensors Multi-HAL.
The sensors work on all platforms except Nagara, but there the problem is caused by blobs, and not this migration.

[u-mr1] common-treble: Switch Sensors Multi-HAL to AIDL v2

---

vintf/manifest.xml

Move the FPC HAL to its own project VINTF fragment. This
will allow us to avoid duplicating code and, for example,
exclude the FPC module from the build using a single flag.
The change from [FPC PR](https://github.com/sonyxperiadev/vendor-sony-oss-fingerprint/pull/78) has been applied to the master branch,
which is used starting from the `s-mr1` branch. For `s-mr1` and `t-mr1`,
I submitted this separate pull request. Since the VINTF structure has
changed significantly starting with the `u-mr1` branch, the patch is
simply incompatible.

[s-mr1] vintf: Move fingerprint entry to its own project

---

CommonConfig.mk
common-treble.mk
vintf/4.19/framework_compatibility_matrix.xml
vintf/4.19/manifest.xml
vintf/5.10/framework_compatibility_matrix.xml
vintf/5.10/manifest.xml
vintf/5.15/framework_compatibility_matrix.xml
vintf/5.15/manifest.xml
vintf/5.4/framework_compatibility_matrix.xml
vintf/5.4/manifest.xml
vintf/vendor.nxp.nxpnfc.xml

The new AIDL HAL covers the entire list of NXP NFC chips,
from PN547C2 to SN300U, meeting all our needs.
It is possible that the Yodo platform will need to fork the
latest version of NXP NFC HAL due to the new dynamic
protection control feature, but all devices from Seine to
Nagara platform are working perfectly.

[u-mr1] common-treble: Switch NXP NFC HAL to AIDL

---

common.mk

Audio policy volumes are tuned for each device individually,
so we cannot provide a generic version. On some devices, the
values may differ from the generic version by a few units,
which is completely unnoticeable, while on others, the values
may vary by 1.5-2 times, which could potentially damage the
speaker.

[u-mr1] common: Do not provide generic audio policy volumes

---

vintf/5.15/android.hardware.radio.config.xml
vintf/5.15/android.hw.qcradio_ds.xml
vintf/5.15/framework_compatibility_matrix.xml
vintf/5.15/vendor.hw.qtiradio_ds.xml
vintf/5.15/vendor.hw.qtiradio_ss.xml
vintf/5.15/vendor.hw.radio.ims.xml
vintf/5.15/vendor.hw.radio_ds.xml
vintf/5.15/vendor.hw.radio_ss.xml

Sync entries with the latest ODM release and OSS configuration.
The configuration is compatible with upcoming ODM and fixes RIL on the Nagara platform,
unfortunately it is probably incompatible with the Yodo platform. In the future we will return
to this when Yodo gets the necessary blobs and the Nagara platform synchronizes with them
since it was ported to the same kernel version.
Fixes: https://github.com/sonyxperiadev/bug_tracker/issues/847, fixes: https://github.com/sonyxperiadev/bug_tracker/issues/860

[u-mr1] Fix RIL for Nagara platform

---

common-treble.mk
vintf/5.4/framework_compatibility_matrix.xml

Provide the android.hardware.secure_element-service.nxp service in order to have the
ability to communicate with Secure Element hardware (eUICC, for example).
The eSIM functionality was tested on the Nagara and Columbia platforms using OpenEUICC.
Please note that LPA is mandatory for the eSIM functionality to work, so it will not work on "pure"
AOSP. The OSS alternative for EuiccGoogle is OpenEUICC.
<details>
<summary>Screenshot</summary>
</details>

[u-mr1] common-treble: Add android.hardware.secure_element-service.nxp

---

vintf/5.4/android.hardware.radio.config.xml
vintf/5.4/android.hw.qcradio_ds.xml
vintf/5.4/android.hw.qcradio_ss.xml
vintf/5.4/framework_compatibility_matrix.xml
vintf/5.4/vendor.hw.qtiradio_ds.xml
vintf/5.4/vendor.hw.qtiradio_ss.xml
vintf/5.4/vendor.hw.radio.ims.xml

Sync entries with the v6+ ODM release.
`libdsutils` requires a patch to work on Blair targets, otherwise netmgrd won't work.
The library from the v5 release works fine

[u-mr1] vintf: 5.4: Sync with the v6+ ODM release
