- sepolicy/file_contexts
Add SELinux for
https://github.com/sonyxperiadev/device-sony-kitakami/blob/master/rootdir/init.kitakami.rc#L97
https://github.com/sonyxperiadev/device-sony-kitakami/blob/master/rootdir/init.kitakami.rc#L103
> sony-common: update file_contexts

- rootdir/init.common.rc
> create new socket directory for nfc

- sepolicy/file_contexts
from system/bin to system/vendor/bin
> sony-common: update policy path for new vendor blobs

- common.mk
for use when is possible
https://android.googlesource.com/platform/frameworks/av/+/08945c44a97d3749cc48f860eb4e01e57183ad90%5E%21/#F0
> sony-common: enable video offload

- power/power.c
- Set low power thresholds on sleep and on POWER_HINT_LOW_POWER
- Set normal power thresholds at any other point
* Note these values may need tweaking for a good result
Needs testing on all devices & better threshold values are needed
> power : add simple cpuquiet / rqbalance interactions

- common.mk
- power/power.c
Allow customization for users in the properties, rather than hardcoding
the values.
Thanks to @kholk for the help.
> powerhal: Store Values in properties

- common.mk
- power/power.c
Add PowerHAL Additions from m-mr1
> PowerHAL cpuquiet/rqbalance interactions

- rootdir/init.common.rc
this was submitted by someone, but i can't find it in pull request
anymore ...
> fix ril on encrypted device

- fingerprint/fingerprint.c
- fingerprint/fpc_imp.c
Fixes some issues with delete and enroll
> Fingerprint Updates

- Android.mk
> Sony-common: allow loire platform

- overlay/frameworks/base/core/res/res/values/config.xml
this was moved to targets also http://www.google.com/oha/rdf/ua-profile-kila.xml is not valid
> sony-common: remove mms_useragent

- rootdir/init.common.rc
01-01 23:46:04.353   325   325 E qdutils : setIdleTimeout:Unable to open /sys/devices/virtual/graphics/fb0/idle_time node Permission denied
> sony-common: Update Graphics Permissions

- rootdir/init.common.rc
> Finally unbreak dualsim :)

- liblights/lights.c
Add a check for 12-bit backlight using max_brightness sysfs file
while retaining compatibility with 8-bit.
I could have added 0-32bit backlight compatibility but that would
have uselessly increased computational complexity to the library
since we actually use only 8-bit or 12-bit backlight in our
devices.
> lights: Add 12-bit backlight compatibility

- rootdir/init.common.rc
Don't be afraid! This can give a nice performance boost under heavy load
Needs the ZRAM driver upgrade: https://github.com/sonyxperiadev/kernel/pull/895
> Configure Zram on all devices, if enabled

- rootdir/init.common.rc
Also restrict system services to system background cpuset
> Add support for top-app cpuset

- Android.mk
Change-Id: I4325d73a5057f9facc07507ad1fccea5a565789c
> sony: common: Add support for the tone platform

- fingerprint/fpc_imp_loire.c
> [m-mr1] Fix Fingerprint on loire

- brcm_fmradio/brcm-uim-sysfs/uim.c
Update firmware path and UART port.
Change-Id: I70e729f3261310df720a25fe9ca71648d50080b1
> sony: common: brcm bt fm: Update UIM parameters

- fingerprint/fpc_imp_kitakami.c
Change-Id: I6dd62beccf36c18f4e43df9a0f0e7d8de6c8eeb8
> FPC: fix kitakami FPC on N

- overlay/packages/apps/Settings/res/values/config.xml
> sony-common: enable storage manager

- common.mk
> sony-common: force HAL1 to msm8974

- fingerprint/fingerprint.c
- fingerprint/fpc_imp_kitakami.c
https://hastebin.com/epevesagat.pl
> sony-common: fix fpc warning build

- Android.mk
> sony-common: fix qcom bt

- brcm_fmradio/libfmjni/android_fm.cpp
- brcm_fmradio/libfmjni/android_fmradio_Receiver.cpp
fix such of warnings in build like https://hastebin.com/qasapimeva.js
> sony-common: brcm_fmradio: fix warnings

- seccomp/mediacodec-seccomp.policy
- seccomp/mediaextractor-seccomp.policy
> sony-common: update seccomp policy

- overlay/packages/services/Telephony/res/values/config.xml
https://android.googlesource.com/platform/packages/services/Telephony/+/android-7.1.1_r25/res/values/config.xml#76
Change-Id: I6dec5a044237d97d01bfacc1675cbf6e20d8a804
> sony: common: overlay: Remove deprecated entry

- brcm_fmradio/brcm-uim-sysfs/Android.mk
- brcm_fmradio/brcm-uim-sysfs/include/uim.h
- fingerprint/Android.mk
- fingerprint/fpc_imp_loire.c
Change-Id: Iccef908b21d0f49b13e78b616724f70e3a2fabde
> [n-mr1] sony: common: Unify FPC and BRCM BT FM implementation for 3.10 and 3.18

- CommonConfig.mk
- common.mk
currently the property is not picked up
> sony: common: move rqbalance enablement to common.mk

- rootdir/init.common.rc
Add permissions so that our ExtendedSettings will be able to
change the resolution and refresh rate on-the-fly.
> [COMMON] Add permissions to set display resolution

- rootdir/init.common.rc
It should be added per platform.
Change-Id: Id6eead02b09ef902e1c5678ca66584e2c68f35f8
> [master] sony: common: init: Remove max_comp_streams

- treble.mk
readme camera device hal https://android.googlesource.com/platform/hardware/interfaces/+/android-8.0.0_r9/camera/
> sony-common: binderize camHAL

- CommonConfig.mk
- compatibility_matrix.xml
- manifest.xml
kanged from marlin
https://android.googlesource.com/device/google/marlin/+/android-8.0.0_r3/compatibility_matrix.xml
https://android.googlesource.com/device/google/marlin/+/android-8.0.0_r3/manifest.xml
> [DO NOT MERGE]sony-common: add Vendor Interface Object

- common.mk
WallpaperPicker needs to be added, self explanatory...
> WallpaperPicker needs to be added.

- treble.mk
second / duplicate 
android.hardware.graphics.mapper@2.0-impl
should be
android.hardware.graphics.mapper@2.0-service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sonyxperiadev/device-sony-common/334)
> Fix duplicate entry

- liblights/lights.c
- rootdir/init.common.rc
adam ported this from angler which unmatch k4.4 sys path change
> 8.0 lights

- rootdir/init.common.srv.rc
Welcome SELinux enforcing mode
Tested on suzu
+
https://github.com/sonyxperiadev/device-sony-sepolicy/pull/304
No denials so far so good!
> [master] Fix permissions for critical services

- rootdir/init.common.rc
- rootdir/init.common.srv.rc
commonize init stuff
Change-Id: I902d56149e0546fa52789a537bcc85ca30ee5190
> [o-mr0] sony: common: init: Move common stuff from platform

- rootdir/init.common.rc
- rootdir/init.common.srv.rc
Move common init stuff between loire, tone and yoshino platforms.
> [master] Move common stuff from platforms

- rootdir/init.common.srv.rc
- rootdir/vendor/etc/gps.conf
1. Update gps.conf from wahoo
2. Add xtra daemon as service
3. Add system group to xtra since GPS Hal (system_server) will write location sock_file.
There is progress with GPS.
> [master] New GPS fixes

- manifest.xml
gnss service is built already, so add it in manifest to explicitly declare usage.
Change-Id: Ic39cf0f6edd636c6c30c1e4e9b1b571ea705ffc7
> manifest: add gnss service

- rootdir/system/vendor/etc/audio_effects.conf
> Audio effect UUID

- android_filesystem_config.h
- common-perm.mk
- common-prop.mk
Reverts sonyxperiadev/device-sony-common#415
more work needed 
it causes adreno crash on yoshino
> Revert "8.1 bringup"

- rootdir/system/vendor/etc/audio_effects.conf
Idem https://github.com/sonyxperiadev/device-sony-common/pull/420
> [N-mr1] Audio effect UUID

- common-prop.mk
* No longer exists in AOSP codebase.
> Remove multiwindow debug flag

- CommonConfig.mk
* This flag has been removed and thus it's not needed.
> Remove EXTENDED_FONT_FOOTPRINT flag

- CommonConfig.mk
* Nile needs to set it to true.
> Allow overriding TARGET_NO_RECOVERY

- common-packages.mk
* This package is being built globally
* See : https://android.googlesource.com/platform/build/+/android-8.1.0_r15/target/product/core_minimal.mk#96
Change-Id: I70aaf469acc29ded3cf5bb24ab112a76b36a7835
> Remove wificond from device makefiles

- manifest.xml
Test: compile; adb shell compiled_vts_binary
Bug: 38499208
Change-Id: I55d6384e88c1839d04be00dab0345ae5a365ab42
> Enable radio service 1.1

- common-treble.mk
* Since we moved to media_profiles_V1_0.xml
Treble OMX should be working just fine.
> Reenable Treble OMX

- common-packages.mk
- common.mk
- rootdir/Android.mk
- rootdir/vendor/bin/init.qcom.devstart.sh
- rootdir/vendor/bin/init.qcom.ipastart.sh
- rootdir/vendor/etc/init/devstart.rc
- rootdir/vendor/etc/init/hw/init.common.rc
- rootdir/vendor/etc/init/ipastart.rc
following wahoo e0fc60024568efaf2bed7fccbe9c3e59201ab75a
4a2b3affdafb5d7f05b03ac61335c1dd77aa7feb
> common: move write inits to scripts

- hardware/qcom/Android.mk
> common: use time-services from aosp

- rootdir/vendor/bin/rdclean.sh
> common: Make vendor script use vendor shell and vendor toybox

- manifest.xml
> Reorder manifest.xml

- common-treble.mk
Change-Id: Ib7a23e59f38a6fbeaba3060aaebca63447261f9c
> Build sony fingerprint HIDL HAL

- manifest.xml
bug:62685361
Change-Id: I0dcd17b70bf52ef82dc9c094650033c4be3e0d1e
> Add widevine service to manifest

- rootdir/init.common.rc
Port commit https://github.com/sonyxperiadev/device-sony-common/commit/4b2af3ea9daba83332581d20ea49e240ae27c2d3 to n-mr1 branch
> init: charger remove partition mount

- common-treble.mk
- manifest.xml
> common: binderize sensors HAL

- common-prop.mk
Taken from:
* https://android.googlesource.com/device/google/marlin/+/f4b5315f48096edaa617f46f5f0c316e524ef6d9
* https://android.googlesource.com/device/google/wahoo/+/2ced5331261a7303d870e86741b3a67875539a81
> Set more volume steps for voice call and media

- common-init.mk
- rootdir/Android.mk
part of commit ebef1c489eb4318118b841591716dc084c6b9f43
> common: remove all xtra binary traces

- common-treble.mk
Signed-off-by: Dusan Beldedovski <dusan.beldedovski@sony.com>
> Add boot control HAL

- rootdir/vendor/etc/init/hw/init.common.rc
the same driver same paths are used by all platforms move it to common repo
> PowerHal: move all needed perm to common

- manifest.xml
> binderize boot control

- rootdir/vendor/etc/init/cnss-daemon.rc
This reverts commit 983c110205df215938629696bd2b6dc27897e2f0.
> Revert "cnss-daemon.rc: set net_admin for cnss-daemon"

- overlay/frameworks/base/core/res/res/values/config.xml
more of a nitpick, but the vibration is on the strong side. Reduce it to
match stock's value
> Reduce default vibration strength

- rootdir/vendor/etc/init/adsprpcd.rc
- rootdir/vendor/etc/init/hw/init.common.rc
- rootdir/vendor/etc/init/sensors.rc
```bash
$ git cherry-pick -x e8792bfabc1ead641bcddc33d77c6704ee55550a
$ git cherry-pick -x 308ba92cf65c4961f070967f729376baef52178
$ git cherry-pick -x b2cf8f50153e8ece6e42238bc1eed3b2a2066053
```
> back-port init script changes from master

- hardware/liblights/service.cpp
- hardware/power/expatparser.c
- hardware/power/rqbalance_halext.c
- misc/libpolyreg/polyreg.c
Some old quickfixes I still had lying around.
> Fix some C++ compiler warnings

- config.fs
> add perms for imsdatadaemon and ims_rtp_daemon

- common-packages.mk
* This package will show a dialog asking user
to reboot their device whenever they remove
or insert a SIM card.
> common-packages: Build SimDetect

- rootdir/vendor/etc/data/dsi_config.xml
Add dsi_config configuration for Starlord: SDM636, SDM660.
> [COMMON] dsi_config: Add parameters for Starlord (636/660)

- rootdir/vendor/etc/data/netmgr_config.xml
Add parameters for Starlord (SDM660 class), required for
SDM660 and SDM636.
> [COMMON] netmgr_config: Add parameters for Starlord (636/660)

- CommonConfig.mk
This reverts commit ecafa08fab498f1e5208ffce0b4f9142f339d486.
> Revert "BOARD_KERNEL_CMDLINE: disable kpti"

- common-treble.mk
Allow devices to select a 64-bit camera implementation.
> common: allow 64-bit camera provider

- hardware/gpt-utils/gpt-utils.cpp
Sending the same PR as https://github.com/sonyxperiadev/device-sony-common/pull/655 to p-mr1 branch; assuming that this was requested.
> gpt-utils: dereference symlinks pointing to device path 

- rootdir/vendor/etc/data/dsi_config.xml
- rootdir/vendor/etc/data/netmgr_config.xml
This configuration is necessary in order to get a working modem on SoMC Kumano.
> [COMMON] Add modem (netmgr/dsi) configuration for SM8150

- common.mk
- rootdir/vendor/etc/gps.conf
Might wanna overhaul it while we're at it...
Needs https://github.com/sonyxperiadev/vendor-qcom-opensource-location/pull/22 and https://github.com/sonyxperiadev/repo_update/pull/119
> [WIP] Readd gps conf

- common-prop.mk
https://source.android.com/devices/storage/adoptable#fixing-double-encryption
> common-prop: avoid double encryption

- common-prop.mk
> Remove HWUI properties

- rootdir/vendor/etc/init/adspstart.rc
- rootdir/vendor/etc/init/cdspstart.rc
- rootdir/vendor/etc/init/hw/init.common.rc
- rootdir/vendor/etc/init/ipastart.rc
- rootdir/vendor/etc/init/slpistart.rc
> rootdir: Prefix Xstart_sh services with "vendor."

- common-packages.mk
- common-treble.mk
- vintf/manifest.xml
And also add some bt packages
Audio HAL also might need updates to `mixer_paths` https://github.com/ExplosiveLobster/device_sony_suzu/commit/535bb5dc7df965b69a823dd3b8ba292ec7224813
> [master] Audio bump to 5.0

- overlay/frameworks/base/core/res/res/values/config.xml
Fix the pinner service to pin the right files.
> [COMMON] Fix pinned files

- common-prop.mk
- common-treble.mk
- rootdir/vendor/etc/init/hw/init.common.rc
I mainly made this PR to spite Angelo.
> [WIP] Init optimizations

- rootdir/vendor/etc/data/dsi_config.xml
For some reason, additional lines went through.. let's fix it.
> [COMMON] [URGENT] vendor: data: dsi_config: Fix data format for Talos

- rootdir/vendor/etc/apns-conf.xml
We already supported it, so let's enable it. :D
> [master] APN: Enable IPv6 for China Mobile/Unicom

- common-packages.mk
- common-perm.mk
- overlay/packages/apps/CarrierConfig/res/xml/vendor.xml
These features are supported but they have never been enabled.
Enable them.
> [COMMON] [Q-MR1] Enable VoLTE, VoWiFi, eMBMS, eUICC

- common-init.mk
- rootdir/Android.bp
- rootdir/vendor/etc/init/cnd.rc
This is the init script for the cnd daemon used in the CnE stack.
> [COMMON] common: Add cnd init script for CnE stack

- rootdir/vendor/etc/apns-conf.xml
Extracted rom stock firmware "H8266_Customized DE_1313-6279_52.1.A.3.49_R3C"
E-Plus got merged into O2
Synced the newest O2 changes
> rootdir: apns: Germany: Update O2 & remove E-Plus

- vintf/manifest.xml
They are already defined by new hidl manifest.xml.
> [R] vintf fixes of wifi from MarijnS95

- vintf/vendor.hw.dataservices.xml
- vintf/vendor.hw.radio.uceservice.xml
ODM v1 for Android 11 introduces a few new interfaces.
> [COMMON] [R/ODMv1] Update versions and add new interfaces to dataservices

- overlay/frameworks/base/core/res/res/values/config.xml
We use nearly the same brightness options
so move brightness options from device repos
to common repo
> overlay: Add common brightness options

- common-binds.mk
- rootdir/vendor/etc/init/bindmount-apps.rc
- rootdir/vendor/etc/init/bindmount-misc.rc
Fixes https://github.com/sonyxperiadev/bug_tracker/issues/640
I don't know if this fixes VoLTE entirely, but the title of that issue is clearly `Exception "vendor.qti.iwlan package not found"`, not `VoLTE is broken`.
@jerpelea Please rebase master.
> [COMMON] [Q/R] Add missing VoLTE bindmount folders

- rootdir/vendor/oem/modem-config/S122.1/modem.conf
- rootdir/vendor/oem/modem-config/S125.1/modem.conf
- rootdir/vendor/oem/modem-config/S125.2/modem.conf
- rootdir/vendor/oem/modem-config/S249.1/modem.conf
- rootdir/vendor/oem/modem-config/S255.1/modem.conf
- rootdir/vendor/oem/modem-config/S260.1/modem.conf
- rootdir/vendor/oem/modem-config/S261.1/modem.conf
- rootdir/vendor/oem/modem-config/S54.1/modem.conf
- rootdir/vendor/oem/modem-config/S57.1/modem.conf
- rootdir/vendor/oem/modem-config/S58.1/modem.conf
- rootdir/vendor/oem/modem-config/S8604.1/modem.conf
- rootdir/vendor/oem/modem-config/S9093.1/modem.conf
- rootdir/vendor/oem/modem-config/S9161.1/modem.conf
- rootdir/vendor/oem/modem-config/S9162.2/modem.conf
- rootdir/vendor/oem/modem-config/S9162.3/modem.conf
for https://github.com/sonyxperiadev/bug_tracker/issues/659
As suggested by @MarijnS95
> Adding several NOBA modem configurations as a fix #659 

- rootdir/vendor/etc/data/netmgr_config.xml
Add configuration for external 5G modem SDX55
> [COMMON] netmgr_config: Add configuration for SDA865 / SM8250 + SDX55

- rootdir/vendor/etc/data/dsi_config.xml
Add configuration for external 5G modem SDX55
> [COMMON] dsi_config: Add configuration for SDA865 / SM8250 + SDX55

- hardware/tftp/Android.mk
This patchset enables support for the external modems and the SM8250 SoC.
> [COMMON] Enable support for external modems and SM8250

- CommonConfig.mk
- common-init.mk
- rootdir/Android.bp
- rootdir/vendor/etc/init/authsecret.rc
- rootdir/vendor/etc/init/spu.rc
- vintf/android.hardware.authsecret_v1.0.xml
- vintf/vendor.hw.radio.internal.xml
- vintf/vendor.qti.spu.xml
This patchset adds the new services for 4.19 BSPs and Kona.
> [COMMON] Add new services for 4.19-based BSPs

- rootdir/vendor/etc/init/bindmount-apps.rc
IMS is broken with the wrong path, although it is still broken after this fix...
> [r-mr1] common: Fix ims bindmount path

- rootdir/vendor/etc/apns-conf.xml
And sync with https://www.o2apn.de/
> rootdir: apns: Germany: O2: Enable IPv6

- rootdir/vendor/etc/init/hw/init.common.rc
A few minor changes to make offline charging work again.
This patch set has been successfully tested on Nile Pioneer (Xperia XA2) and Ganges Kirin, Mermaid, (Xperia 10 and Xperia 10 Plus) devices.
> [r-mr1] Fix offline charging mode

- common-binds.mk
- rootdir/vendor/etc/init/bindmount-apps.rc
- rootdir/vendor/etc/init/bindmount-misc.rc
Signed-off-by: Luofan Chen <clfbbn@gmail.com>
> init: Make bindmount consistent with software binary image

- common-odm-camx.mk
> [t-mr1] common-odm-camx: Zambezi typo fix

- rootdir/vendor/etc/data/dsi_config.xml
- rootdir/vendor/etc/data/netmgr_config.xml
Add data configuration for SoC Waipio and Kalama.
> [t-mr1] vendor: data: Add configuration for SoC Waipio&Kalama

- common.mk
- overlay/WifiResCommon/Android.bp
- overlay/WifiResCommon/AndroidManifest.xml
- overlay/WifiResCommon/res/values/bools.xml
- overlay/WifiResCommon/res/values/integers.xml
- overlay/WifiResCommon/res/values/strings.xml
- overlay/frameworks/base/core/res/res/values/config.xml
Might have to get into S/T/U/V too
> [r-mr1] Move Wifi config to own RRO

- common-packages.mk
- common-treble.mk
- rootdir/vendor/etc/gps.conf
Switch GNSS HAL to AIDL. Update gps.conf and add required dependencies for it.
Tested on: <details>
<summary>Seine, Murray, Sagami, Columbia</summary>
</details>
> [u-mr1] Switch to GNSS AIDL HAL

- CommonConfig.mk
- common-treble.mk
- vintf/4.19/framework_compatibility_matrix.xml
- vintf/5.10/framework_compatibility_matrix.xml
- vintf/5.15/framework_compatibility_matrix.xml
- vintf/5.4/framework_compatibility_matrix.xml
- vintf/android.hardware.vibrator_v1.0.xml
- vintf/android.hardware.vibrator_v1.2.xml
The QTI Vibrator AIDL HAL can handle all hardware from Seine to Yodo.
> [u-mr1] common-treble: Switch Vibrator HAL to AIDL

- common-treble.mk
- rootdir/vendor/bin/init.qcom.adspstart.sh
- rootdir/vendor/bin/init.qcom.cdspstart.sh
- rootdir/vendor/bin/init.qcom.slpistart.sh
- rootdir/vendor/etc/init/adsp-sensorspdr.rc
- rootdir/vendor/etc/init/sdsp-sensorspdr.rc
- rootdir/vendor/etc/init/sensors.rc
Switch Sensors Multi-HAL. Improve ADSP/CDSP/SLPI start scripts to avoid possible race conditions.
The change is compatible with all current platforms; it just requires some minor adjustments for
each platform. I will push the remaining changes later this evening.
Tested on: Seine, Sagami, Murray, Columbia, Yodo.
> [u-mr1] common-treble: Switch Sensors Multi-HAL to AIDL
